### ISSUE TITLE
[DataEntryTable] For LastPass users, first cell has extra icon

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1011]
LastPass (a password manager browser plugin) irrelevantly inserts its icon into the first cell of the Data Entry table:
![Screen Shot 2021-02-12 at 10 40 22](https://user-images.githubusercontent.com/6411521/107788752-c666bb80-6d1e-11eb-86b5-e9cb45cb2ede.png)

Related: #399

**Comment by jasonleenaylor** [comment]
Appears to have been fixed by changes since Feb 2021.
