### ISSUE TITLE
Create Mongo script to determine if any projects are missing Word.Guid or Sense.Guid

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1014]
As part of #1013, it would be good to create a short Mongo script to run on our active databases to check to see if any projects are missing GUIDs on their `Word`s or `Sense`s.

We need to check for the following items:

- FrontierCollection & WordCollection
  - All entities have a top level `guid` key
  - All `senses[]` have a `guid` key

An example of a **correct** entry:

```json
{
"_id":{"$oid":"60200badc239e4231ef4cfa0"},
"guid":{"$binary":"2ljEdo4ZTkyhZmWBTOrfKw==","$type":"3"},
"vernacular":"a",
"plural":"",
"senses":[{"Glosses":[{"Language":"en","Def":"n"}],"SemanticDomains":[{"Name":"Universe, creation","_id":"1","Description":""}],"accessibility":"Active","guid":{"$binary":"vBbCqfVFG0ud8hFmBqYs0g==","$type":"3"}}],
"audio":[],
"created":"2021-02-07T15:47:57.5811167Z",
"modified":"2021-02-07T15:47:57.5811317Z",
"accessibility":"Active",
"history":[],
"partOfSpeech":"",
"editedBy":[],
"otherField":"",
"projectId":"60200b88c239e4231ef4cf9d",
"note":{"Language":"en","Text":""}
}
```

I don't think this needs to be checked into the repo as it will be a one-time-use script.

**Comment by imnasnainaec** [comment]
Similar: #506, #557, #612

**Comment by jmgrady** [comment]
I ran the following queries against the mongo database container on the live server.

For each collection I listed the documents that did not have a top-level guid by running the following query:
```
mongo CombineDatabase -eval 'db.CollectionName.find({ senses : { $elemMatch : { guid : {$exists: false}}}},{ senses : 1, projectId : 1}).toArray()'
```
To list the senses without a guid, I ran the following query:
```
mongo CombineDatabase -eval 'db.CollectionName.find({ senses : { $elemMatch : { guid : {$exists: false}}}},{ senses : 1, projectId : 1}).toArray()'
```
I have attached the query result files.  It looks like there are a lot of entries without GUIDs.  Does mongo offer a function to create a guid as part of an update?  Also, if anyone knows of a better way to run the query, I'd like to know.
[guidQueries.zip](https://github.com/sillsdev/TheCombine/files/5973536/guidQueries.zip)

**Comment by johnthagen** [comment]
It looks like in `master` we only automatically repair the FrontierCollection words (not the history WordCollection history).

You should be able to repair all of the frontier words for a project by making a GET request to: `/v1/projects/{projectId}/words/frontier`

To trigger this via the frontend, go to Data Cleanup | Create Character Inventory

<img width="338" alt="char-inv" src="https://user-images.githubusercontent.com/10340167/107805273-1c455e80-6d33-11eb-954f-3026ec927087.png">

Would you mind trying this on one of the project IDs that returned in the frontier mongo results?

**Comment by jmgrady** [comment]
OK. Let's try this again.  This time exercising more data sensitivity and pasting the right queries:
I ran the following queries against the mongo database container on the live server.

For each collection I listed the documents that did not have a top-level guid by running the following query:
```
mongo CombineDatabase -eval 'db.CollectionName.find({ guid : {$exists: false}},{ vernacular : 1, projectId : 1}).toArray()'
```
To list the senses without a guid, I ran the following query:
```
mongo CombineDatabase -eval 'db.CollectionName.find({ senses : { $elemMatch : { guid : {$exists: false}}}},{ senses : 1, projectId : 1}).toArray()'
```
The Frontier data show 13 projects that are missing GUIDs for their entries.  I think it would be good to try to create a script to repair the records since opening the project in the GUI only repairs the Frontier collections and it requires that the user be a member of the project so one would probably be scripting that anyway.

I'll create a list of the projects by name and post that on slack.  Knowing which projects are affected may help us decide the best way to proceed.

**Comment by johnthagen** [comment]
Backend GUID example vs Python [`uuid.uuid4()`](https://docs.python.org/3/library/uuid.html#uuid.uuid4)

```
backend: 832e66dc-8cc2-4efc-b55c-3b3589b027b2
python:  fe776caa-d087-424f-8106-ff9781083363
```

**Comment by imnasnainaec** [comment]
@jmgrady #1013 is ready to merge whenever this issue is dealt with.

**Comment by jmgrady** [comment]
The mongo shell commands to create the missing GUIDs are:
```
use CombineDatabase
db.FrontierCollection.update({ guid: { $exists : false} }, { $set : { guid : UUID() }}, { multi: true})
db.FrontierCollection.update({ senses : { $elemMatch : { guid: {$exists: false}}}}, { $set : { "senses.$.guid" : UUID() }}, { multi: true})
db.WordsCollection.update({ guid: { $exists : false} }, { $set : { guid : UUID() }}, { multi: true})
db.WordsCollection.update({ senses : { $elemMatch : { guid: {$exists: false}}}}, { $set : { "senses.$.guid" : UUID() }}, { multi: true})
```

**Comment by jmgrady** [comment]
Improved mongo shell commands are:
```
use CombineDatabase
db.FrontierCollection.updateMany({ guid: { $exists : false} }, { $set : { guid : UUID() }})
db.FrontierCollection.updateMany({}, { $set : { "senses.$[element].guid" : UUID() }}, { arrayFilters: [ { "element.guid": {$exists: false}}]})
db.WordsCollection.updateMany({ guid: { $exists : false} }, { $set : { guid : UUID() }})
db.WordsCollection.updateMany({}, { $set : { "senses.$[element].guid" : UUID() }}, { arrayFilters: [ { "element.guid": {$exists: false}}]})
```

**Comment by imnasnainaec** [comment]
Added to [MongoDB 1-time maintenance scripts](https://docs.google.com/document/d/1L9WjBZqBNVfxk5KiIQo5Fzjsetv4JuwGU0wuYKDRtWo)
