### ISSUE TITLE
Can't upload a LIFT file to TheCombine

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/TheCombine#1051]
I've been trying to upload a LIFT file into Combine, but it's not working. I guess you can see the projects I've created this afternoon. Don't bother with the first one, but no. 2 was an attempt in Firefox (86.0, 64-bit) in Wasta 20.04. The upload spinner just spun for 1.5 hours or so before I stopped it. Then I tried in Chromium: that time the cursor spun for nearly 3 hours. The 4th try was after I cleared the Chromium cache, even though I'm sure I cleared it recently, long after my last try at using Combine.

Try 2 has around 230 words in it; try 3 has 30-something; try 4 has 43, I think. But my FLEx DB has 11,000+ entries.

I'm attaching my zipped LIFT file here. Can you see anything wrong with it--corrupt index perhaps? Maybe I need to repair something with the FLEx tools; I have been doing a good bit of merging, deleting, attaching grammatical info, etc., in the DB. Any advice would be appreciated! 
[Rapoisi FLEx cleanup.zip](https://github.com/sillsdev/TheCombine/files/6073423/Rapoisi.FLEx.cleanup.zip)

**Comment by imnasnainaec** [comment]
@KimB2017 Are any of these multiple attempts to upload to the same project or is each attempt with a new project?

**Comment by KimB2017** [comment]
Each attempt is a new Combine project, but I'm trying to upload a single 
LIFT database file to Combine. There should be several older, archived 
or deactivated projects under my account name as well--last time I tried 
might have been around last October but at that time there was a bug 
with re-importing an edited Combine LIFT file back into FLEx. I 
abandoned those Combine projects so that we could continue to use FLEx 
without causing conflicts with the stuck-in-Combine LIFT data. I think I 
read that it is not possible to *delete* an unwanted Combine project?

*Kim Blewett*
Language Technology Consultant (LSS)
SIL Papua New Guinea

**Comment by imnasnainaec** [comment]
@KimB2017 I'm investigating now. On development builds of The Combine, your file `Rapoisi FLEx cleanup.zip` is able to upload in 10 seconds, but when I try on thecombine.app, it stalls as you described--it actually gives a 502 error right away in the console, so it will spin perpetually if allowed, not actually doing anything.

**Comment by imnasnainaec** [comment]
@KimB2017 Can we delete the following four old Rapoisi projects that are archived:
* Rapoisi RWC cleanup
* kyx RWC cleanup U
* Rapoisi RWC cleanup 2
* Rapoisi RWC cleanup 3
?

**Comment by imnasnainaec** [comment]
Fixed in #1054. To be released with v0.6.7.

**Comment by imnasnainaec** [comment]
@KimB2017 v0.6.7 has been released to www.thecombine.app and we are able to import your entire file!

Would you like us to delete your old projects?
* archived: Rapoisi RWC cleanup, kyx RWC cleanup U, Rapoisi RWC cleanup 2, Rapoisi RWC cleanup 3
* recent failed imports: Rapoisi FLEx cleanup, Rapoisi FLEx cleanup 2, Rapoisi FLEx cleanup 3 (chromium), Rapoisi FLEx cleanup 4 (cleared cache)

**Comment by KimB2017** [comment]
Yes please, delete all the old ones. Many thanks!

**Comment by KimB2017** [comment]
So I've tried again in v 0.6.7 with the same project LIFT file. But it's still spinning and not uploading any entries. I tried first in Chromium (it's the Snap-installed version for Ubuntu Focal, in case that makes a difference). Then I tried in Firefox. Same failure in both. If you tell me where to find a log file I'll send it to you, if that helps.

**Comment by jmgrady** [comment]
I was able to import the project LIFT file that you posted but only
    after I had restarted the server (I will see if I can figure out if
    & why that had an effect) and when I imported the file by
    specifying it when I created the project.  If I create the project
    first and then go to the project page to import the zip file, it
    hangs as you have described.
    
    On 3/5/21 12:54 PM, Kim Blewett wrote:
    
    
      
      So I've tried again in v 0.6.7 with the same project LIFT file.
        But it's still spinning and not uploading any entries. I tried
        first in Chromium (it's the Snap-installed version for Ubuntu
        Focal, in case that makes a difference). Then I tried in
        Firefox. Same failure in both. If you tell me where to find a
        log file I'll send it to you, if that helps.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sillsdev/TheCombine/issues/1051#issuecomment-791582341",
"url": "https://github.com/sillsdev/TheCombine/issues/1051#issuecomment-791582341",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
      Jim
      "In practice, the difference between theory and practice is
        greater than it is in theory."

**Comment by jmgrady** [comment]
I have restarted the effected services and it will import for me from both the project creation screen and the _Import Data_ section of the project page.
