### ISSUE TITLE
No such command as `npm certify`

### ISSUE THREAD

**Issue by merchako** [sillsdev/TheCombine#116]
The README says,

> Run `npm certify` and `npm start` from the project directory to install dependencies and start the project

But there's no such command as `npm certify`. Could it be a typo? This has me stuck.

**Comment by SamDelaney** [comment]
Sorry about this. That was an old command that got removed and has not been re-added yet. Try running
`dotnet dev-certs https`
and
`dotnet dev-certs https --trust`

**Comment by merchako** [comment]
Does that mean I should install the .Net SDK, not just the runtime?

**Comment by SamDelaney** [comment]
Yes, .NET Core SDK is required. Updated the README and closing.
