### ISSUE TITLE
Pressing Shift-Tab to move back to edit the username causes frontend to try to log in

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1197]
Maybe related to #1187 

1. Open Register Page
2. For Your Name type: user
3. Press Tab
4. Press Shift-Tab to go back to try to edit "Your Name" field
5. Registration page is redirected to login page before being able to do anything

## TODO

- [ ] The backend should be able to handle a blank string (`""`) sent to check if a username or email exists 
- [ ] The frontend should not send a request to check if a username or email exists if the input field is blank (`""`)

**Comment by imnasnainaec** [comment]
I think this preceded #1187. It may be from #1136.
If email or username is blank and you shift focus away from the field, then it causes an error with the check for whether email/username is taken.

**Comment by johnthagen** [comment]
Should the frontend not send a blank string? Though, ideally the backend should be able to handle receiving a blank string.

**Comment by imnasnainaec** [comment]
> Should the frontend not send a blank string? Though, ideally the backend should be able to handle receiving a blank string.

Both. Let's update the initial post in this issue with a two-task todo. I think this is a "good first issue" for the interns.
