### ISSUE TITLE
Adding a user to a project does not add them to Current Users

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1211]
1. Register two users
2. Login with user 1
3. Create a project
4. Open project-settings
5. Add User > user 2
6. They do not show up immediately under Current Users
7. They only show up if you Hard refresh the page

**Comment by johnthagen** [comment]
This was discovered while reviewing #1210, but it exists before that PR.

**Comment by imnasnainaec** [comment]
This was fixed in #1277
