### ISSUE TITLE
Enforce function return type in ts?

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1223]
Should global function return type be enforced in typescript linting?

**Comment by johnthagen** [comment]
The return type for functional React components should be `ReactElement`.

- https://stackoverflow.com/a/57363438

**Comment by johnthagen** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md
