### ISSUE TITLE
Investigate possible issue in identifying users for analytics

### ISSUE THREAD

**Issue by jasonleenaylor** [sillsdev/TheCombine#1237]
The analytics library is supposed to identify users after they login so that we track all a users activity to an account. This should even identify the same user if they login from multiple computers. Looking at the data that we are getting I suspect something in this is not working properly.

![image](https://user-images.githubusercontent.com/2295227/124296147-7e4e0700-db0e-11eb-9a8b-0e6730ca92f6.png)

There are large clusters of users in several cities that look suspicious.

**Comment by johnthagen** [comment]
For reference, analytics were added in #1108

**Comment by johnthagen** [comment]
I suspect that given that `REACT_APP_ANALYTICS_WRITE_KEY=WoE6Qf2AeEUdQMQZBd0PpqSztHQYWRxj` is in the default `.env` for development that when developers are testing locally and wiping out the database, multiple duplicate test users are being reported.

**Comment by johnthagen** [comment]
Confirmed that after I created a new user in development it showed up in mixpanel. This makes sense given we are using the same key for all deployments. Probably we should bin the development different than the production server.

https://github.com/sillsdev/TheCombine/blob/9a69089401205385720e136c0ef950b1e6bf2a5e/.env#L2

https://github.com/sillsdev/TheCombine/blob/9a69089401205385720e136c0ef950b1e6bf2a5e/deploy/group_vars/qa/main.yml#L10

https://github.com/sillsdev/TheCombine/blob/9a69089401205385720e136c0ef950b1e6bf2a5e/deploy/group_vars/server/main.yml#L10
