### ISSUE TITLE
Leaving create character inventory page causes the users project to be unselected

### ISSUE THREAD

**Issue by JacobHaimes** [sillsdev/TheCombine#1240]
When leaving the create character inventory page, the current project becomes unselected. This appears to only affect the setting page as you are still able to make changes such as merge duplicates and character changes as if the project is still selected. However, in the setting tab, the project is not selected and other options such as exporting and interface languages become unusable.

**Comment by imnasnainaec** [comment]
This was from #1117 where we changed `CharacterInventoryType.RESET` from to  "CHARINV_RESET" to "RESET". That string needs to be reverted, since "RESET" is the value of `StoreActionTypes.RESET`, which shows up in multiple reducers.
