### ISSUE TITLE
Lock horizontal scroll bar to the bottom of page in review entries

### ISSUE THREAD

**Issue by JacobHaimes** [sillsdev/TheCombine#1252]
Currently, if you use a mouse to scroll, you have to scroll to the bottom of the review entires page to use the horizontal scroll bar and then have to scroll back up the page to make changes. The horizontal scroll bar should stay at the bottom of the page so the user doesn't have to continuously scroll up and down.

**Comment by imnasnainaec** [comment]
This may require turning off the horizontal scroll of the `material-table` and enforcing a minimum width of the table that can overflow the page width, so that we only use the window's horizontal scroll bar.

**Comment by imnasnainaec** [comment]
It appears resolving this would require a significant refactor within `@material-table/core`. Closing the issue until it is brought up by a user.
