### ISSUE TITLE
UI does not respond to 413 error on upload

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#1254]
When importing a large project (currently > 100MB), the server will return an HTTP response of 413, _Request Entity Too Large_.  The UI does not report the error to the user and the cursor stays set to the _busy_ animation.

**Comment by johnthagen** [comment]
Related to #1125

**Comment by imnasnainaec** [comment]
Related: #202

**Comment by jasonleenaylor** [comment]
We believe this is now covered by #1125
