### ISSUE TITLE
[ProjectSettings] Re-render after a user in the project is updated

### ISSUE THREAD

**Issue by WeJamUS** [sillsdev/TheCombine#1260]
Currently the page does not change after updating a user even though the user update did take effect. It would be nice for users to see the effects of their change immediately without having to refresh the page.

**Comment by imnasnainaec** [comment]
A non-refresh way to force the reload is: click on the setting heading twice to hide and reveal that section. But that is still inconvenient.

**Comment by imnasnainaec** [comment]
Related: #1211
