### ISSUE TITLE
Add maintenance/admin messages to frontend

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#1297]
Add the ability to display maintenance and administration messages to the user, such as planned downtime for backups and upgrades.

The [GitLab Broadcast Messages](https://docs.gitlab.com/ee/user/admin_area/broadcast_messages.html) are an example implementation.
See also GitLab's documentation on how to [Customize the Help and sign-in page messages](https://docs.gitlab.com/ee/user/admin_area/settings/help_page.html).

**Comment by johnthagen** [comment]
Adding backend as we'll want to be able to store these messages (site-wide singletons) in the database and be able to query them from the backend.

**Comment by johnthagen** [comment]
As some inspiration, here is a Django plugin that enforces singleton database tables: https://github.com/lazybird/django-solo

Could use this as an example of how to expose a singleton model instance.
