### ISSUE TITLE
Projects list is empty on Site Settings page.

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#1301]
If I log into _The Combine_ as a user that is a site admin and navigate to the Site Settings page, the list of Projects is empty instead of listing all projects in the database.  This may be related to Issue #1030.

**Comment by imnasnainaec** [comment]
This errors on GET endpoint `/v1/projects`.
Possibly related: project creation (with GET `/v1/projects/duplicate/{projectName}`) and saving character inventory (with PUT `v1/projects/{projectId}`) also fail with 500 errors in the console.

**Comment by imnasnainaec** [comment]
Problem identified: #1284 was not followed with a necessary database update.

**Comment by imnasnainaec** [comment]
@jmgrady's database fix, clears all invite tokens:
```db.ProjectsCollection.updateMany({}, {$set : { "inviteToken" : [] }})```
