### ISSUE TITLE
"Export Failed" icon persists at the top of the screen even after exiting out of the project page.

### ISSUE THREAD

**Issue by WeJamUS** [sillsdev/TheCombine#1311]

**Comment by imnasnainaec** [comment]
The export/download feature is intentionally disconnected from the Project Settings page for a couple reasons: (1) Users can work on other things if it's a large download that takes a while; (2) Site admins can export any project from the SiteSettings page.

However, some small possible improvements comes to mind: (a) when switching projects, we could reset the export status if it is in the failed state; (b) we could add text to the tooltip to the effect of "click to dismiss".
