### ISSUE TITLE
[DataEntry] Allow entry with multiple analysis languages

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1333]
"12. H [Entry] Has the ability to enter data in two analysis languages been enabled yet? We didn’t see a way to turn on entering in both languages at the same time, even though we set up our project to have two analysis languages."

**Comment by jasonleenaylor** [comment]
Consider making the glossing language user specifc.

**Comment by jasonleenaylor** [comment]
Also allow the user to pick more then one - for non workshop scenarios

**Comment by jasonleenaylor** [comment]
Closing awaiting a specific requested user scenario that needs this.
