### ISSUE TITLE
[MergeDuplicates] When done with sets of potential duplicates to find, give user option to load next set

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1345]
Give the user the option to continue merging when the last set of suggested duplicates is completed.

From: D&LS
"27. M [Merge] Want a way to choose how many “sets” are in a round of cleanup."

**Comment by johnthagen** [comment]
This will likely be implemented in or around:

https://github.com/sillsdev/TheCombine/blob/master/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx

**Comment by johnthagen** [comment]
From Jason:

- Add pop up dialogue after 12th item is confirmed asking the user if they would like to either "Stop" or "Continue"

**Comment by johnthagen** [comment]
Call stack (going up) for how `GoalStatus.Completed` is set.

https://github.com/sillsdev/TheCombine/blob/c47f5d6a4b1d9bbe219e3485c0986aed2841fb7c/src/types/goalUtilities.ts#L72

https://github.com/sillsdev/TheCombine/blob/da8eadfa28429da30ce1ac5ddc56e9ea8bb00b97/src/components/GoalTimeline/Redux/GoalActions.ts#L48

https://github.com/sillsdev/TheCombine/blob/da8eadfa28429da30ce1ac5ddc56e9ea8bb00b97/src/components/GoalTimeline/Redux/GoalActions.ts#L61

**Comment by johnthagen** [comment]
Completed MergeDup rendering stack (top down):

https://github.com/sillsdev/TheCombine/blob/da8eadfa28429da30ce1ac5ddc56e9ea8bb00b97/src/goals/DefaultGoal/BaseGoalScreen.tsx#L60

https://github.com/sillsdev/TheCombine/blob/da8eadfa28429da30ce1ac5ddc56e9ea8bb00b97/src/goals/DefaultGoal/BaseGoalScreen.tsx#L28

https://github.com/sillsdev/TheCombine/blob/da8eadfa28429da30ce1ac5ddc56e9ea8bb00b97/src/goals/MergeDupGoal/MergeDupComponent/index.tsx#L9

**Comment by imnasnainaec** [comment]
The frontend `Goal` corresponds with the backend `UserEdit`, the backend model has no concept of `completed`, an entirely frontend distinction. The only time it is applied is when loading in the goal history (i.e., the user edit history) from the backend. Every goal in that history list is marked as completed, so the user can see the result (in the case of merge duplicates and character inventory) and undo (in the case of merge duplicates).
