### ISSUE TITLE
[ReviewEntries] Add loading screen

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1421]
When the user selects 1000 entries per page, it can take a long time to load and isn't clear that something in loading. Add a loading overlay when loading for more than a few seconds.

(If this isn't done in time for the next RWC workshop, temporarily reduce max number of entries.)

**Comment by johnthagen** [comment]
See:

- https://stackoverflow.com/questions/55835316/is-there-a-way-to-manually-fire-the-isloading-animation-from-a-custom-action-in
- https://material-table-core.com/docs/api/props/mt_prop_isLoading

**Comment by imnasnainaec** [comment]
We may be able to make use of https://material-table-core.com/docs/api/props/mt_prop_isLoading in https://github.com/sillsdev/TheCombine/blob/master/src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTable.tsx#L40-L81.

**Comment by imnasnainaec** [comment]
We probably want the https://github.com/sillsdev/TheCombine/tree/master/src/components/LandingPage to pop up over the review entries table the same way we currently display the TreeView over https://github.com/sillsdev/TheCombine/blob/master/src/components/DataEntry/DataEntryComponent.tsx#L170-L185

**Comment by johnthagen** [comment]
Performance analysis using a powerful Desktop computer:

- 100: 4s
- 1000: 2min 18s; Pressing "Wait for browser 7 times

**Comment by johnthagen** [comment]
The `material-table` `isLoading` prop provides a nice built in UI for this:

<img width="605" alt="Screenshot 2022-02-04 130134" src="https://user-images.githubusercontent.com/10340167/152579780-68c72619-e199-499a-bd42-c3e962942aed.png">

**Comment by johnthagen** [comment]
Asked a discussion question on `@material-table/core` about this: https://github.com/material-table-core/core/discussions/482

**Comment by jasonleenaylor** [comment]
Look into using useEffect to turn off the 'isLoading' in the MaterialTable

**Comment by imnasnainaec** [comment]
Working on an update to Material Table that will automatically set `isLoading` to `true` when changing page or changing rows per page (as it already does when editing a row): https://github.com/imnasnainaec/core/tree/isLoading-on-page-change

**Comment by imnasnainaec** [comment]
We may want to consider moving our data querying/filtering/sorting to the backend and use https://material-table.com/#/docs/features/remote-data.

**Comment by imnasnainaec** [comment]
This is no longer necessary with the in-progress switch to `material-react-table`.
