### ISSUE TITLE
Split word during merge

### ISSUE THREAD

**Issue by Rapdorian** [sillsdev/TheCombine#143]
I want to be able to tag senses during a merge that should be split off into their own word for further processing later. All senses with their state set to seperate should be put in their own new word.

I have a graph demonstrating the use case for what I am asking for
![image](https://user-images.githubusercontent.com/7032450/60834446-524d5480-a186-11e9-8bb4-b2e8dd4228a0.png)

**Comment by SamDelaney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split word during merge #143](https://trello.com/c/OrHNsQJy/151-split-word-during-merge-143)

**Comment by Rapdorian** [comment]
There are three cases you need to take care of during merging.

- __[DUPLICATE]__ Add senses's src word to parent's history, do not add sense to parent's senses

- [SENSE] Add both sense and word id to parent's history

- [SEPARATE] Add both sense and word id to a separated word not the parent
