### ISSUE TITLE
[DataEntry] Improve feedback to users on duplicate words

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1449]
**To Reproduce**

1. Go to project setting and switch Autocomplete to Off;
2. Go to Data Entry;
3. Select a domain (e.g., 1.1);
4. Submit a new entry (e.g., vernacular "Donut" and gloss "Doughnut");
5. Press "Exit" to return to the tree;
6. Select a different domain (e.g., 1.2);
7. Submit the same entry;
8. An alert pops up saying:
> thecombine.app says
> This word is already in the database: Donut, Doughnut
> [OK]
9. Go to Data Cleanup and select Review Entries;
10. The word shows up with both domains.

Ideally, the alert should say that the domain is being added to the existing entry.
~Possibly, the user should be given options: add new domain to existing entry; create new entry with the new domain; cancel the submission for the new domain.~

**Comment by jasonleenaylor** [comment]
Is this alert a result of processing the response from the backend? I don't think we initially implemented it with an alert, we just silently added the domain and showed the entry in the list of 'added' entries with a slightly different look. We have made some significant changes since the original work though.

**Comment by imnasnainaec** [comment]
Related: #1584, #1585

**Comment by jasonleenaylor** [comment]
We have changed our behavior for this so the feedback suggested here is no longer necessary. The word now appears in the recent entries list giving the look of success, since we do add the new semantic domain.
