### ISSUE TITLE
Non-admin users cannot update character inventory

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1472]
Non-admin users have access to all goals (Merge Duplicates, Review Entries, Create Character Inventory), but are prevented from submitting changes in the Character Inventory.

**To Reproduce**

1. Open/create a project with at least one entry.
2. Go to user settings and invite another user to the project.
3. Log in as the other user.
4. Click on Data Cleanup > Create Character Inventory.
5. Select one of the characters, press the "Accept" button, then the "Save".
6. See the 403 error pop up.

**Expected behavior**

One of two options:
* ~Allow users to update character inventory;~
* For users who can't update character inventory, don't allow access this goal in the first place.

**Comment by johnthagen** [comment]
I was able to confirm this bug on `master`.
