### ISSUE TITLE
Cannot read property 'srcWord' of undefined

### ISSUE THREAD

**Issue by SamDelaney** [sillsdev/TheCombine#148]
Happens when dragging a card in merge duplicates. Not sure how to reproduce yet.
![Debugging3](https://user-images.githubusercontent.com/20246757/60914191-a0c62600-a24e-11e9-9541-c0fed7b7a29f.PNG)

**Comment by Rapdorian** [comment]
closing because the code that triggers this no longer exists. This bug is with how merge dups was written before we used a library for drag and drop
