### ISSUE TITLE
[CreateProject] Move import/upload option above language selection

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1493]
"19. M [Create Project] Move “Upload” question above the WS questions, since if you are uploading, you shouldn’t have to answer those."

**Comment by johnthagen** [comment]
Currently the Vernacular and Analysis Languages are required fields, so you can't create a project, even with upload, without setting those.

Should that be changed as well?

**Comment by imnasnainaec** [comment]
> Currently the Vernacular and Analysis Languages are required fields, so you can't create a project, even with upload, without setting those.
> 
> Should that be changed as well?

That would be part of #1336
