### ISSUE TITLE
Remove permission 2 (formerly Unused) from live server

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1494]
Follow on to #1491 

This task should be completed after the next release is publised.

> @jmgrady When this is released, we will need to run a one-time database migration script on the live server to remove all `2` Permission objects from all Users. This will allow this value can be reused safely in the future if needed.

**Comment by jmgrady** [comment]
The following command will remove the `Unused` permission on the Live server once #1491 is released.
```
kubectl exec -it deployment/database -- mongo CombineDatabase
db.UserRolesCollection.updateMany({}, { $pull: { permissions: 2 }})
```
13 Dec 2021: This has been applied to the database on the QA Server.

**Comment by jmgrady** [comment]
07 Jan 2022: This has now been applied to the database on the Live server as well.
