### ISSUE TITLE
Update to react-scripts v5

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1521]
ESlint is currently capped at 7.x rather than 8.x due to `react-scripts`

Our current version: `4.0.3`
Latest: `5.0.0`

https://www.npmjs.com/package/react-scripts

**Comment by johnthagen** [comment]
Upstream build issue: https://github.com/facebook/create-react-app/issues/11756

**Comment by johnthagen** [comment]
A large number of our dependencies rely on `safe-buffer`, which internally relies on Node's `Buffer`. Fixing this without introducing invasive changes to our build process would be difficult.

**Comment by johnthagen** [comment]
This is on the milestone for CRA 5.0.1.

**Comment by imnasnainaec** [comment]
Resolved in #1886
