### ISSUE TITLE
"hasAvatar" does not always get set to "true" when an avatar is selected for a user

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#1534]
**Describe the bug**

Under certain conditions, when setting up a user the user's avatar file location is saved in the database but the "hasAvatar" field is not updated to "true".

**To Reproduce**

1. Register a new user and login as the user;
2. Open the _User Settings_ dialog;
3. Click on the blank avatar;
4. Click _Browse_ and select an image file to be the avatar image;
5. Click _Save_;
6. Click _Save_;
7. Login to _The Combine_ as the new user from another device;
8. Image is not displayed.

In addition, if one has access to the server, one can list the document in the database `UsersCollection`:
 - Run: `kubectl exec -it deployment/database -- mongo CombineDatabase`
 - List the document for the user that was just created:
```
> db.UsersCollection.find({username: "jmg116"}).pretty()
{
	"_id" : ObjectId("61e6da981330b361b12e5e77"),
	"avatar" : "/home/app/.CombineFiles/Avatars/61e6da981330b361b12e5e77.jpg",
	"hasAvatar" : false,
	"name" : "Me",
	"email" : "******@****.com",
	"phone" : "",
	"otherConnectionField" : "",
	"workedProjects" : {
		
	},
	"projectRoles" : {
		
	},
	"agreement" : false,
	"password" : "eitvUa+yD+sQzvCYZEwRAEHKNhwgujomRXK1qfECYj0CR5P/G3mbDAVjAlySlPxe",
	"username" : "jmg116",
	"uiLang" : "",
	"token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2MWU2ZGE5ODEzMzBiMzYxYjEyZTVlNzciLCJVc2VyUm9sZUluZm8iOiJbXSIsIm5iZiI6MTY0MjUxOTE5MywiZXhwIjoxNjQyNTMzNTkzLCJpYXQiOjE2NDI1MTkxOTN9.9UtaqR5H2nO2kQjumgRqhMLnfR66nvjdioU-UPohNIU",
	"isAdmin" : false
}
```   
Note the `avatar` and `hasAvatar` fields.

**Expected behavior**

_The Combine_ should display the user's avatar on all devices.

**Environment:**

Further investigation is needed but it seems to only happened when connected to _The Combine_ from an Android device using a Chromium based browser (_Chrome 97_ or _Brave 1.34_) but not Firefox 96.  The problem was see with _The Combine_ running on the Live server and running on a NUC.  The problem has not happened when connecting to _The Combine_ from an Ubuntu Desktop.

**Comment by jmgrady** [comment]
Problem also occurred when connecting to _The Combine_ using Chrome on iOS.  It did not occur when connecting to _The Combine_ using Microsoft Edge on Android.

**Comment by imnasnainaec** [comment]
One way to avoid this possible race condition: disable the User Settings save button when the avatar dialog is open, confirm that the dialog doesn't close until avatar upload is finished, and add `hasAvatar: !!avatar` to the input of `updateUser()` in the User Setting's `onSubmit` function.
