### ISSUE TITLE
[NewEntry] Shift focus on ENTER if selected suggestion matches types vernacular

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1538]
In project settings, turn Autocomplete On.

In data entry, when adding a new entry, start typing a vernacular similar to an existing entry, then arrow down to select that entry and press enter. The expected behavior is that the "Select an entry" dialog will pop up. It does this by shifting focus away from the vernacular input field, triggering its `onBlur` function. The one instance this doesn't work is: if what you typed is identical to the selected vernacular. Then the suggestion menu closes, but you still have to press TAB or click somewhere else for the dialog to pop up. The logic needs to be added to check for this case when the user presses enter.

**Comment by johnthagen** [comment]
I was able to reproduce this issue on `master`.

**Comment by johnthagen** [comment]
This should be implemented in or around:

https://github.com/sillsdev/TheCombine/blob/c4c155fc01d94d8207df378d7aa94757c181bd49/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L574

**Comment by johnthagen** [comment]
I believe this behavior is happening because when you select an entry from the drop down list that matches what is already typed, the state does actually change (no value change) so the render/update cycle is not triggered.

**Comment by johnthagen** [comment]
@imnasnainaec 

> The logic needs to be added to check for this case when the user presses enter.

What about if the user simply Left clicks on the identical dropdown instead of `Enter`?

**Comment by johnthagen** [comment]
I was not able to get any of these callbacks to fire when autocompleting a selection for which the exact selection was already filled in:

https://github.com/sillsdev/TheCombine/blob/c4c155fc01d94d8207df378d7aa94757c181bd49/src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx#L42-L60

**Comment by imnasnainaec** [comment]
I would try `onClose`, except we want it in the ENTER and left-click cases and *not* in the ESC case.
