### ISSUE TITLE
Change UpdateUserEditStep to use a Edit GUID rather than a Goal index

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1541]
Rather than indexing a `List<Edit>`  in `UpdateUserEditStep()` to select which `Edit`  based on a `GoalIndex` use a, reference the `Edit` but it's `Guid`.

This would allow removing `goal.index` and obliviate the need to do #1539

**Comment by johnthagen** [comment]
Frontend: Need a way to define a `Goal` without a GUID yet.

**Comment by imnasnainaec** [comment]
For discussion: when we update a goal/edit, do we want:
- updated and moved to the end of the list,
- updated and left in place,
- the old version left in place and the updated version (with the same guid) added to the end of the list?
