### ISSUE TITLE
[NewEntry] Note+Audio are lost when a new entry is determined to be a duplicate

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1584]
Two parts:

- [x] Note
- [ ] Audio

**Describe the bug**

When a new entry is determined in the backend to be a duplicate of an existing entry, the semantic domain of the new entry is added to the existing entry and the new entry is not created. When that happens, any note or audio added before submitting the new entry is completely lost.

**To Reproduce**

1. In project settings, turn off Autocomplete.
2. Go to Data Entry and select any domain.
3. Add a new entry (e.g., "vern", "gloss") with no note or audio and press Enter
4. Add another entry with the exact same vernacular and gloss, but this time add a note and a recording before pressing Enter
5. There will be an alert that the entry you added is a duplicate, but the note and audio you made are nowhere to be found.

**Expected behavior**

The audio of a duplicate entry should be added to the entry which is being duplicated.
The note should be appended to the existing entry (;-separated?). (What do we do if the new note is in a different language than the existing note?)

**Comment by imnasnainaec** [comment]
Note is taken care of in the backend with #1615.
Audio requires changing how duplicate is passed to and handled by the frontend.

**Comment by johnthagen** [comment]
I confirmed this bug exists for Notes on current `master` branch (prior to #1615).

**Comment by johnthagen** [comment]
During the fix for audio, consider refactoring `WordIsUnique` to be more semantically accurate/decomposed:

- https://github.com/sillsdev/TheCombine/pull/1615#issuecomment-1072394861
