### ISSUE TITLE
[DataEntryTable] A duplicate new entry that updates an existing entry doesn't add it to Recent/Existing Entries

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1586]
**Describe the bug**

When a new entry is a duplicate of an existing entry, the semantic domain of the new entry is added to the existing entry instead of the new entry being created. However, when that happens, the updated existing entry should be added either to the Recent Entries above the New Entry row or the the side box of Existing Entries in the domain.

**To Reproduce**

1. Go to project setting and switch Autocomplete to Off;
2. Go to Data Entry;
3. Select a domain (e.g., 1.1);
4. Submit a new entry (e.g., vernacular "Donut" and gloss "Doughnut");
5. Press "Exit" to return to the tree;
6. Select a different domain (e.g., 1.2);
7. Submit the same entry;
8. Deal with the pop-up that tells you it was a duplicate.
9. Observe that the entry is not visible (but if you click done, then click the same domain again, that entry should now be visible in Existing Entries)

**Comment by johnthagen** [comment]
This also happens when `Note`s are added when a duplicate vern/gloss are entered with a new `Note`:

- https://github.com/sillsdev/TheCombine/pull/1615#issuecomment-1072382594
