### ISSUE TITLE
Migrate backend models and tests to CompareNETObjects

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#1599]
We should be able to remove a significant amount of boilerplate from our Models and tests by migrating all of our custom equality logic to [`CompareNETObjects`](https://nuget.org/packages/CompareNETObjects).

In tests, use [`ShouldCompare()`](https://github.com/GregFinzer/Compare-Net-Objects/wiki/Test-Extensions#shouldcompare)

**Comment by jasonleenaylor** [comment]
Since CompareNetObjects uses reflection and we may want to keep the IComparable this tasks seems bigger than the benefit.
