### ISSUE TITLE
Improve the landing page experience

### ISSUE THREAD

**Issue by jasonleenaylor** [sillsdev/TheCombine#1604]
- [x] 1. Rename 'Register' button to 'Sign Up'
- [ ] 2. Include a 'call to action' paragraph with an additional 'Sign Up' button in the content area
- [x] 3. Add a link to the 'Sign Up' in the 'Account' documentation

**Comment by johnthagen** [comment]
For 3. we would need to figure out if it's possible to add a relative link to an MkDocs project.

**Comment by johnthagen** [comment]
One of the _additional_ issues with adding relative links within the MkDocs projects is that when the docs are served outside of the App itself (e.g. hosted on GitHub pages) or distributed offline (if users wish to read the docs without installing the entire tool), these links won't work.

**Comment by johnthagen** [comment]
For 3., it looks like relative links should work according to the MkDocs maintainer 5 years ago: 
- https://github.com/mkdocs/mkdocs/issues/192#issuecomment-352325894
