### ISSUE TITLE
JWT token expiration time incorrect

### ISSUE THREAD

**Issue by Micah-Schiewe** [sillsdev/TheCombine#162]
Since the server time is local time (when it should be UTC), the tokens (generated in UTC) are not expiring properly.

**Comment by Micah-Schiewe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Invalid Authorization token ignored #71](https://trello.com/c/63wikDlc/97-invalid-authorization-token-ignored-71)

**Comment by SILMarkFuller** [comment]
As per @jasonleenaylor this is not an MVP problem and will not be considered an issue
