### ISSUE TITLE
User Interface Language not selectable, yet it is sticky

### ISSUE THREAD

**Issue by MattGyverLee** [sillsdev/TheCombine#1684]
I'm working with a dozen French-speakers this week using theCombine online. In previous versions, interface and semantic domains seemed to follow the language of the browser. SemDom can now be configured separately in project settings, but I now see no way in-app to configure the interface language. I was able to fix it, for now, by hacking the browser local storage...and that should work for me until the end of the workshop.

**To Reproduce**
Some users get the French Interface, but if the user has English as their browser language  (or something else) at first usage of TheCombine. English will "Stick" in the current version.

1. Login in a browser with English as a default.
2. Try to Change the language in interface, not possible.
3. Change main browser language to French.  Refresh. Combine doesn't change.
4. Change Regional Settings and Windows Language to French. Refresh. Combine doesn't change.
Workaround:
5. Open the browser inspector.
6. Go to the Application Tab
7. Under Local Storage, choose https://theCombine.app
8. Under i18nextLing, change to fr-FR.  Refresh. No effect.
9. Under user, change uiLang to "fr-FR". Refresh. This seems to work. UI is in French, and persists (presumably until cookies get cleared).

**Expected behavior**
Choosing French as the interface language, or thCombine consistently following browser language.

**Environment:**
Windows: Chrome and Edge.
thecombine.app live version, active version from yesterday.

**Comment by imnasnainaec** [comment]
Related: #706

**Comment by imnasnainaec** [comment]
On macOSX: a refresh is sufficient in Chrome/Chromium v112; restarting the browser works in Firefox v112.

**Comment by jasonleenaylor** [comment]
Will be addressed in the fix for #706
