### ISSUE TITLE
Lift Export has exactly duplicated entries.

### ISSUE THREAD

**Issue by MattGyverLee** [sillsdev/TheCombine#1701]
**Describe the bug**

WeSay data was imported into FLEx for a bulk edit, which was exported directly to LIFT. The Lift was imported into TheCombine. After merging duplicates and getting the white screen (https://github.com/sillsdev/TheCombine/issues/1700), I exported each of the 5 projects to LIFT for FLEx importing. Most of the projects imported without complaint. FLEX Beta's new "Import from TheCombine" took the Kangou-2 zip file, but then it choked because multiple entries were duplicated, sometimes multiple times back to back, with the same details and same GUID, making the LIFT invalid. (The FLEx import tells you exactly which GUIDs are duplicated.) Can you check the history to see at what point the dups were introduced? 

Maybe it happened when they undid a merge by dragging a sense back. Maybe it happened during the merge itself. I don't think the entries were duplicated like this before TheCombine.

This isn't urgent for the team, as I removed the dups manually and imported into FLEx to prepare for publication.   

**To Reproduce**

0. I've added imnasnainaec to the Kangou-2 Project. 
1. Download the Kangou-2 LIFT export from TheCombine. 
2. Try to import into FLEx Beta (9.1.10+) via the "Import from The Combine".
3. FLEx will tell you which entries are duplicated.
4. FLEx tells you to notify tech support of the program that created the LIFT file (which I'm doing now).

I have the offending LIFT if needed, but you should get the same dump from TheCombine. I think there were about 10 entry guids out of nearly 2 thousand that had multiple entries, but I was working quickly and didn't take note.

**Expected behavior**

I expect GUIDs not to be duplicated.

**Environment:**

- OS: [e.g. Windows/Android]
- Browser Version [e.g. Chrome 89, Firefox 90]

**Comment by imnasnainaec** [comment]
I was able to cause some entry duplication by clicking a "Save & Continue" button a second time when it was slow to process after the first click. That may have contributed to your issue. We need to add a safeguard against double-clicking that button.

**Comment by MattGyverLee** [comment]
That makes sense. We had about a 5-second delay on some machines before the
next entry loaded.
-M

**Comment by imnasnainaec** [comment]
FLEx import duplicate entry bug fixed by #1740.
