### ISSUE TITLE
Captcha checkmark sometimes takes a full minute or more to load after the page finishes loading.

### ISSUE THREAD

**Issue by MattGyverLee** [sillsdev/TheCombine#1702]
**Describe the bug**

We had 10 computers banging on TheCombine.app from the same (slowish) router IP in Cameroon. The login page would load quickly, but the Captcha often took more than a minute to load into the blank space. The only clue to the user in the meantime that something is missing is that the login button is greyed out.

I realize that the Captcha is an external service you don't control...and African traffic is often underprioitized or suspect. We kept running into this issue each morning. I wonder if we were getting throttled by the Captcha service, or if the live instance wasn't equipped with an API that was fast enough. 

I'm not sure how reproducible this error is, but I wanted to get it out there.

**Comment by imnasnainaec** [comment]
This should be resolved by #3249, which will be out in the next release.
