### ISSUE TITLE
Update Mongo to later version

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#1703]
The Combine is using MongoDB 4.4 which was released in July 2020.  MongoDB 5.0 was released in July 2021 and MongoDB 6.0 in July 2022.  The Docker images for MongoDB are currently at 5.0.

[MongoDB Software Lifecycle Schedules](https://www.mongodb.com/support-policy/lifecycles) show the end-of-life date for each version.

The [Release Notes for MongoDB 5.0](https://www.mongodb.com/docs/manual/release-notes/5.0) describe the changes from 4.4 to 5.0.

**Comment by imnasnainaec** [comment]
Our backend uses the MongoDB .NET api and the version we're on (2.14) is already compatible with mongo 5.0:
https://www.mongodb.com/docs/drivers/csharp/#mongodb-compatibility
