### ISSUE TITLE
Semantic Domain refactor

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1721]
We are currently passing the entire semantic domain tree to be handled in the frontend. This is unwieldy, leading to at least one significant issue (#1720). We want to do the work on the server and only pass the needed pieces of the tree to the browser.

- [x] Load semantic domain data into mongo (#1719)
- [x] Update the models/types for semantic domains (#1718)
- [x] Create backend functions to fetch semantic domain data from the database
- [x] Create the api for the frontend getting the data from the backend
- [x] Refactor the frontend TreeView to only request what it needs

**Comment by jasonleenaylor** [comment]
Completed in #1735
