### ISSUE TITLE
Project statistics for admins

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1723]
**Is your feature request related to a problem? Please describe.**

There is a need for project admins to have high-level statistics of the words collected so far in a project.

**Describe the solution you'd like**

For project owner and admins, along-side the Data Entry and Data Cleanup options in the top bar, add a third option: Statistics. This should lead to a page that shows a table of all semantic domains with the number of words collected in each domain. The first column should be indented/nested according to the depth of the domain. We could also color rows depending on how many words are in each domain, to help quickly identify domains with few words.

The solution is based off of this spreadsheet: 

**Acceptance Tests**

1. The Statistics Button is available for Admin and Owners
2. The Statistics Button is not available for regular users
3. The Statistics Button loads a page with a table displaying a row for each Semantic Domain category
4. Each row in the table displays the following columns:
4.1 The Semantic Domain Number
4.2 The Semantic Domain Name
4.3 The Count of Senses in the project which contain the Semantic Domain for the row
5. Kevin Warfel thinks it is useful.

** Development Plans **

- [x]  The Statistics Button for Admin / not available for users
- [x]  The Statistics Button loads a page with a table displaying a row for each Semantic Domain category
- [x] Each Row displays Domain Number && Name && Senses

On the frontend we expect to modify the NavigationButtons component to add a Statistics button. We will be adding a new Statistics Component to display the table and any other future tools for workshop administrators.

On the backend we expect to add a new StatisticsService and StatisticsController to provide the API endpoints needed to support the frontend. These will use the WordRepository and SemanticDomainRepository to provide the data. A single endpoint for the 1,792 domains seems better than one call for each domain.

The next step is to regenerate the frontend bindings to the API and modify our frontend code to call this.
Then we will add a table to the Statistics Component to display the data retrieved from the API.

The Details tab of this spreadsheet is our example: https://docs.google.com/spreadsheets/d/1hHiWno2gbG0lcF0LVCxbhRKSJlscb7Ox/edit?usp=sharing&ouid=113698097296021267973&rtpof=true&sd=true

**Comment by jasonleenaylor** [comment]
- [ ] Add Statistics button to the top bar (If the user is an Administrator or Owner)
- [ ] Add Backend method to return semantic domain statistics.
- [ ] Add a Statistics Component to display the collected words for each domain.
