### ISSUE TITLE
Allow merging/deleting of 'safe' Lift imported words and senses 

### ISSUE THREAD

**Issue by jasonleenaylor** [sillsdev/TheCombine#1761]
We want to allow users to clean up existing FLEx data without putting that data at risk.

Add a flag to entries and senses that we import which have data other than 'Lexeme Form', 'Citation Form', 'Gloss', 'Definition', or 'Semantic Domains'.

Disable deletion or merging away of those entries and senses.

Acceptance Tests:
Merge works when it should and not when it shouldn't
All 'safe' fields are handled properly when merged in The Combine
Import into FLEx demonstrates success

Addresses #1750

**Comment by MattGyverLee** [comment]
Thanks for the update. This is a start, but wouldn't that stop you from being able to work with FLEx Data if even grammatical category is filled in? 

I'm curious why TheCombine discards the extra LIFT data in the first place. Was this a temporary limitation for the minimum viable product? Was this to improve performance? 

How much of a performance impact would it be to import and export the whole data structure? How much work would it be to merge the extra fields and add a residue comment or merge message? I wouldn't ever expect the extra fields to be viewed or edited in TheCombine, just retained.
