### ISSUE TITLE
Upgrading to axios version 1.x.x breaks audio recording

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#1930]
**Describe the bug**

When the npm package, axios, is updated to a 1.x.x version, audio recording is broken.

**To Reproduce**

1. Set the version for `axios` to 1.3.4 in `./package.json`
2. Run `npm start`
3. Open an existing project
4. Display the _Review Entries_ screen
5. Click & hold the recording icon to make recording
6. When the button is released, an error is displayed. See attached.
![Screenshot from 2023-02-27 10-30-58](https://user-images.githubusercontent.com/10785548/221607093-32d45508-371c-49d9-937c-f16bc6b33624.png)

**Expected behavior**

No error.  Green _Play_ icon is displayed.

**Environment:**

- OS: Ubuntu 22.04
- Browser Version: Brave Browser, Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by imnasnainaec** [comment]
Axios is on 1.3.5 now (https://github.com/axios/axios/releases/tag/v1.3.5) though I'm not sure what sort of bugfix we'll be looking for to try again.

**Comment by imnasnainaec** [comment]
It's now on [v1.6.1](https://github.com/axios/axios/releases/tag/v1.6.1).

**Comment by jmgrady** [comment]
The 0.x.x branch has been updated to 0.28.0 which now also throws a "400 - Bad Request" error.

**Comment by jmgrady** [comment]
See https://github.com/axios/axios/issues/4406 for some possible solutions.

**Comment by imnasnainaec** [comment]
The issue is resolved when we change from `"content-type": "application/json"` to `"content-type": "multipart/form-data"` in the request header (as read about [here](https://andrewlock.net/exploring-the-dotnet-8-preview-form-binding-in-minimal-apis/#must-set-multipart-form-data-if-sending-files)).
