### ISSUE TITLE
[ReviewEntries] Admin view word history

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#1966]
Each word has a `history` field that lists the ids of all predecessor words (prior to merges, added senses, or other edits). This information is not available to the user. It would be helpful for a project admin to be able to see it, to know (e.g.) what users added semantic domains to a word.

In each row of the Review Entries table, there should be (at the start or end) a button that pops up a read-only view of all the words in the history of that row's word. This button should only be available to project admins.

**Comment by jasonleenaylor** [comment]
History View Requirements

- Display a tree view of the word and its ancestors
  - Words that were merged will have more than one previous version
- Display the user who made each edit
- Display each word in a 'Card' view
- Add permission for word history (Give to Admins and Project Owners initially)
- On the button in Review Entries display the number of edits (Button should be history icon with a 'chip' showing number of edits)

**Comment by imnasnainaec** [comment]
Questions for Kevin **before** demoing the prototype:
- Where/how would you expect to access Word History?
- What would you want to use Word History for?
- What do you expect to see when opening a Word History?

**Comment by imnasnainaec** [comment]
This is low priority for Kevin and Verna.

**Comment by imnasnainaec** [comment]
Closed unless requested. See branch `word-history` for work if issue re-opens.
