### ISSUE TITLE
Permission definitions include roles

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#1983]
The current user permissions are defined in `src/api/models/permission.ts` as:
```
export enum Permission {
  WordEntry = "WordEntry",
  MergeAndReviewEntries = "MergeAndReviewEntries",
  ImportExport = "ImportExport",
  DeleteEditSettingsAndUsers = "DeleteEditSettingsAndUsers",
  Owner = "Owner",
}
```
However, `Owner` is a role, not a permission.  It would be better if we removed `Owner` and add the permissions that are currently restricted to an `Owner`, e.g. `ViewStatistics`.

**Comment by jmgrady** [comment]
Owners can also:

- Archive a project
- Access any goal other than `MergeDups`, `ReviewEntries`, or `CreateCharInv`

**Comment by jasonleenaylor** [comment]
To implement this we will want to define a set of project roles:
Owner: All permissions on the project
Administrator: DeleteEditSettingsAndUsers, ~~Import~~Export, MergeAndReviewEntries, WordEntry
User: WordEntry

We should split import and export permissions and grant only export permissions to Administrator.
