### ISSUE TITLE
[AppBar] Improve layout for narrow windows

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#2251]
The current `AppBar` configuration for `xs` (<600 pixels wide) works alright for 400+ pixel width, but not well on narrower windows (which is the case with many smartphones).

- Add icons that replace the "Data Entry" and "Data Cleanup" text buttons in `xs` (and accompany them on wider windows) and have the text as mouse-over text.
- Add ~~a (?) icon or~~ (i) info button in the `AppBar` that links to the user guide (consulted with Kevin on best Icon)
  - Add icons to the user guide next to their text equivalents

**Comment by jasonleenaylor** [comment]
Kevin has a slight preference for the info button.
