### ISSUE TITLE
Remove nginx configuration for https connections

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#2401]
The configuration of the nginx server can be simplified by removing support for the `default_http_and_https.conf` configuration.  In the Kubernetes environments (Production, QA, & local), all SSL traffic is terminated at the ingress controller so only http traffic is forwarded to the frontend's nginx server.  In the development environment, the nginx server is not running.

The `default_http_and_https.conf` configuration was created for the `docker compose` method for deploying _The Combine_.  This is no longer supported.

**Comment by imnasnainaec** [comment]
Resolved in #2493
