### ISSUE TITLE
Prep for Sep 28 tech demo

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#2467]
Kevin & Danny the presenters

**Comment by jasonleenaylor** [comment]
Kevin is open to all kinds collaboration options, will discuss with @imnasnainaec in early September.

**Comment by imnasnainaec** [comment]
Kevin and Danny are collaborating together over video chat and in Google Drive (The Combine - Project Info > 2023 Sep 28 RWC webinar) and will present together.

**Comment by imnasnainaec** [comment]
Presented! Notes and slides in the Google Drive folder The Combine - Project Info > Documentation and Presentations
