### ISSUE TITLE
Data entry does not display correct senses for a word

### ISSUE THREAD

**Issue by tyasw** [sillsdev/TheCombine#252]
1. Add a word in the data entry component that already exists in the database.
1. Click on the red dot next to the vernacular of the word to bring up the duplicate resolution view.
1. Click on a sense of the duplicate word from the choices.
1. The word becomes grayed out, with the wrong sense.

The data entry table keeps track of words, but it doesn't keep track of which sense to display. Immutable entries display the last gloss of the last sense in the word. There needs to be a way to keep track of which sense and which gloss should be displayed for each word in the list of words.

**Comment by imnasnainaec** [comment]
Resolved by #512
