### ISSUE TITLE
DataEntry sem dom lang doesn't update without refresh or domain change

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#2578]
**Describe the bug**

When you change a project's Semantic Domain Language and return to Data Entry, the language is updated in the domain tree. However, if you click on the most-recently-selected semantic domain (without refreshing or navigating in the domain tree), then the domain name in the header of the Data Entry screen is still in the previous language.

**To Reproduce**

1. Open a project and go to project settings
2. Set the semantic domain language to English
3. Go to Data Entry, navigate to domain 1 Universe, Creation, and click on it
4. See the data entry header says "Domain: Universe, creation (1)"
5. Go to project settings and change semantic domain language to Spanish
6. Go to Data Entry and click on 1 Universo, La Creación
7. See that the data entry header says "Domain: Universe, creation (1)"
8. Click exit, and in the domain tree navigate away from and back to domain 1
9. Click on it and the header is now "Domain: Universo, la creación (1)" (what it should have been the first time)

**Comment by jasonleenaylor** [comment]
Won't fix, unlikely to impact real users.
