### ISSUE TITLE
console error when attempting to invite a new user via 'INVITE BY EMAIL”

### ISSUE THREAD

**Issue by Daneyecgroup** [sillsdev/TheCombine#2675]
**Steps to Reproduce:**
1. Log in to "https://qa-kube.thecombine.app/" with valid credentials.
2. Create a new project in Combine.
3. Navigate to Setting > USERS
4. Click "INVITE BY EMAIL".
5. If we add a new user, Email Invitation is not sent to the new user and we are getting 403 Forbidden (console) error as attached in the screenshot "**403.png**" 

Attached error log file as "**Console Log**".

[Console Log.log](https://github.com/sillsdev/TheCombine/files/12818571/Console.Log.log)
![403](https://github.com/sillsdev/TheCombine/assets/147053060/7a5ba575-9b78-4924-a285-66957dc02f0b)

**Comment by imnasnainaec** [comment]
This bug appeared in June: https://github.com/sillsdev/TheCombine/commit/37b3d1c4f863c1c1052497950a63cb49835584a6#diff-3ccecc09e1e705bf38f7fba104941aa0d23f6cbd64fef278e3d78aee7e348c22
