### ISSUE TITLE
Image in LIFT mis-uploaded as audio.

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#2681]
**Describe the bug**

One of our test LIFT files (https://github.com/sillsdev/TheCombine/blob/master/Backend.Tests/Assets/Natqgu.zip) has 11570 entries when uploaded, none with audio, but one with a JPG file that has been mis-identified as audio. In Review Entries, this results in the following row with a green play icon that doesn't play anything:

![Screenshot 2023-10-05 143049](https://github.com/sillsdev/TheCombine/assets/6411521/136aa825-f882-43ad-97e5-94f10bb2c445)

...along with a console error:
```
SC%20dancer%20small.JPG:1     GET https://thecombine.localhost/v1/projects/651efb39ac2f2466b1f2232a/words/651efb3bac2f2466b1f2685d/audio/download/SC%20dancer%20small.JPG 400 (Bad Request)
```

**Comment by imnasnainaec** [comment]
This appears to be an issue with the original export, not our import. In `Natqgu.lift`, lines 173369-173371:
```
<pronunciation>
<media href="SC dancer small.JPG">
</media></pronunciation>
```

It shouldn't have been classified as a `<pronunciation>`.

**Comment by imnasnainaec** [comment]
There is no `SC dancer small.JPG` in `Natqgu.zip`.

**Comment by jasonleenaylor** [comment]
This is probably a project data issue, I'd need to look at the original FLEx project to be sure, but when choosing a pronunciation file I think you are able to select less than useful files.
