### ISSUE TITLE
Domain tree doesn't fit horizontally in small-width windows

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#2682]
For any domain with 9 children, they start to overflow the right of the window if it is ~<1050px~ <850px wide  (improved in #2683).

**Comment by imnasnainaec** [comment]
Related: #573

**Comment by jasonleenaylor** [comment]
Possibly replace the tree view with only the find box and a 'Find your domain' and showing the single domain that the search results in?
