### ISSUE TITLE
Consider using a third-party authentication library

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#296]
The `UserService ` implements user authentication (and the cryptography associated with it) manually. This is probably a bit dangerous / error prone. Ideally, we could find a supported third-party library that is heavily tested to offload this complexity to.

For example, in the Python/Django ecosystem, authentication is handled by middleware in the framework rather than each individual project: https://docs.djangoproject.com/en/stable/topics/auth/

https://github.com/sillsdev/TheCombine/blob/8f56dd4adbe05c025916a1f601a53db81a5b05d1/Backend/Services/UserApiServices.cs#L31-L62

**Comment by johnthagen** [comment]
Something similar could be said possibly for JWT. In the Python/Django ecosystem third party packages exist to handle all of the nuts and bolts (https://pypi.org/project/djangorestframework-simplejwt/), perhaps something similar exists for C#/.NET Core.

https://github.com/sillsdev/TheCombine/blob/8f56dd4adbe05c025916a1f601a53db81a5b05d1/Backend/Services/UserApiServices.cs#L68-L113

**Comment by jasonleenaylor** [comment]
To handle authentication for the public site we will likely be using Auth0 through the language technology identity project, but we should consider how that impacts the NUC deployment.
