### ISSUE TITLE
Data Entry / Data Cleanup enabled before project is selected

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#298]
1. Register a new user
2. Login with that user
3. Add an avatar to the user
4. Select Data Entry
5. Daily Life | Fire | Burn | Burn
6. Venacular: `burn`; Glosses: `very hot`

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 OPTIONS https://localhost:5001/v1/projects/5ea5dc9c0ef3b50dd8129c03/words
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      Policy execution successful.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.0917ms 204
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST https://localhost:5001/v1/projects/5ea5dc9c0ef3b50dd8129c03/words application/json;charset=UTF-8 239
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      Policy execution successful.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Word"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Post(System.String, BackendFramework.ValueModels.Word) on controller BackendFramework.Controllers.WordController (BackendFramework).
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      Policy execution successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method BackendFramework.Controllers.WordController.Post (BackendFramework) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method BackendFramework.Controllers.WordController.Post (BackendFramework), returned result Microsoft.AspNetCore.Mvc.ForbidResult in 0.0452ms.
info: Microsoft.AspNetCore.Mvc.ForbidResult[1]
      Executing ForbidResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[13]
      AuthenticationScheme: Bearer was forbidden.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action BackendFramework.Controllers.WordController.Post (BackendFramework) in 0.5527ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.8277ms 403
```

This also seems to happen if you create a project, but don't select it yet.

## Expected

If a project hasn't be selected, these UI elements shouldn't be enabled.

**Comment by imnasnainaec** [comment]
I don't think adding the avatar is necessary. It appears to me that simply the act of going to User Settings causes whichever project was most recently opened to be invisibly reopened, so the Data Entry and Data Cleanup buttons start working and the Project Settings option becomes available.

**Comment by imnasnainaec** [comment]
If no project has been opened since login, going to User Settings appears to partially open whichever project is at the top of the list. I say partially, because Review Entries shows the entries from that project, but Data Entry doesn't save anything new to that project and Project Settings only partially loads:
![partialsettings](https://user-images.githubusercontent.com/6411521/83057603-2698be80-a025-11ea-9bf0-028acf27925b.png)

**Comment by imnasnainaec** [comment]
Part of the problem is in https://github.com/sillsdev/TheCombine/blob/master/src/components/AppBar/UserMenu.tsx lines 61-62, where the availability of the Project Settings option within the User Menu is based on a url check and not on a state that holds the active project.

**Comment by imnasnainaec** [comment]
It's the same deal in https://github.com/sillsdev/TheCombine/blob/master/src/components/AppBar/NavigationButtons.tsx where the Data Entry and Data Cleanup buttons are active for any url other than the root.

**Comment by imnasnainaec** [comment]
Work on this issue is in branch AppBarNavigation: https://github.com/sillsdev/TheCombine/tree/AppBarNavigation
