### ISSUE TITLE
Combine displays an error message when user disables microphone access

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#3001]
**Describe the bug**

When a user first connects to The Combine, the browser will ask for permission to use the microphone.  If the user blocks this permission, The Combine displays an error message that says:

> Error getting audio stream! 

**To Reproduce**

1. Navigate to https://thecombine.app
2. When prompted for permission to use the microphone, select "Block"
3. Error message is displayed

**Expected behavior**

While technically correct, this message is not useful to a user and implies that there is a technical failure with The Combine.  Instead, it should say something to the effect of "Recordings are disabled."

In addition,

1. this error message is displayed every time the user displays the launch page, and
2. the "Record" buttons are not disabled - it would be better to tell the user a priori that recording is disabled.

**Environment:**

- OS: [e.g. Windows/Android]
- Browser Version [e.g. Chrome 89, Firefox 90]

**Comment by jmgrady** [comment]
As a follow-up about the "Record" buttons, when permission has not been granted to access the microphone and the user tries to make a recording, there is no indication that recording is disabled - just that the Play icon is not displayed.

**Comment by jasonleenaylor** [comment]
We should probably use this api to check permissions:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions
