### ISSUE TITLE
Port dropDB.bat and seedAdmin.bat to npm TS scripts

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#305]
Currently `dropDB.bat` and `seedAdmin.bat` can only be run on Windows, since they are `.bat` files. Porting them to TypeScript would allow them to be run on any OS.

**Comment by jmgrady** [comment]
Note that for the target systems, the NUCs and thecombine.languagetechnology.org, the git repo is not installed.  The deployment of the app is done through ansible playbooks.  There are several mongodb modules for Ansible.  I would prefer to use these for maintaining the target environments because the Ansible playbooks are idempotent (https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html).  @jasonleenaylor - what are the requirements for pre-installed users, e.g. a known admin user, for the target systems?

**Comment by jmgrady** [comment]
However, I cannot currently connect to the database except by localhost:27017.  Either I need to open up this connection (probably not desired) or there needs to be another mechanism.

**Comment by johnthagen** [comment]
Good point, we wouldn't deploy `npm` onto end servers (it's only needed to *build* the frontend, not run it) so these scripts would strictly be for developers, or as @jmgrady points out, we come up with a more flexible solution.

In past projects, I usually use Python for this kind of thing since it's preinstalled on Linux, but not sure what the common practice is for SIL deployments.

**Comment by jmgrady** [comment]
@johnthagen, @jasonleenaylor 
I had not thought of this either.  Right now, we do not initialize the database at all as far as I know.  We create the empty directory for the db and the MongoDB initializes the files as needed.  Now that you are creating an admin screen we will need to be able to have at least one admin user created who will be allowed to delete users, projects, etc.
Currently, it seems that users only exist in the context of TheCombine app but not the database - no username or password are required to connect to MongoDB and once connected, any database operation can be performed.  I would like to hear your thoughts about this.  Should we use the database to restrict operations? e.g. have a dbadmin who can do anything and a dbuser who can add data and only delete certain types of data?  In general, TheCombine would connect as a dbuser but when the Admin page is entered, then they would login as the dbadmin.  The advantage of this that the administration tasks are separate from the users who are assigned roles for projects, etc.

**Comment by johnthagen** [comment]
> Currently, it seems that users only exist in the context of TheCombine app but not the database - no username or password are required to connect to MongoDB and once connected, any database operation can be performed

This is a good point. Generally speaking, when I've done backends like this the database as a whole is protected by it not being accessible outside the host. So, for example, the Mongo DB listening port would only be exposed to localhost (127.0.0.1) and not externally (0.0.0.0). This allows only processed running on the host (in this case our backend) from accessing the database. The backend can then manage user permissions.

The way admin users currently work (and we'll likely want to change this) is that they can only be created with local access to the host the backend is running on. There is an `isAdmin` attribute stored with users that can only be set to `True` using access to the host. This way, Ansible could set this for a specific user

**Comment by johnthagen** [comment]
or

**Comment by johnthagen** [comment]
Some developers are using Ubuntu 18.04, so this increases the need for this issue.

**Comment by johnthagen** [comment]
@jasonleenaylor I can work on this if you'd like. Is there consensus to port these to TypeScript (we'll probably want to deal with @jmgrady's legitimate needs in a follow on issue)?

**Comment by jmgrady** [comment]
@johnthagen 
I agree that the device setup needs are different than the development needs.  I will create a separate issue for the device setup requirements.  In addition to having a known database admin user, I think we will need a known login for the NUC (i.e. consistent across all NUCs) with sudo privileges.
