### ISSUE TITLE
[Project Settings] Add visual indication of collapsed sections

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#3113]
**Describe the bug**

In a project's Project Settings (gear icon in the top bar), within any of the tabs, you can collapse a section (e.g., "Project Languages" or "Export Project" by clicking on the title of that section. However, there's no indication that the section is collapsed... it just looks like nothing loading in it. And it's very easy to accidentally click on a section header and close the section, then be confused at why the content is missing.

**Comment by jasonleenaylor** [comment]
Probably use an Accordian component from MUI
https://mui.com/material-ui/react-accordion/
