### ISSUE TITLE
[Project Settings] Edge case: brand new owner can remove themselves

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#3114]
A project administrator (e.g., Simon) can remove themselves from a project.
A project owner (e.g., Garfunkel) can transfer project ownership to a project administrator (e.g., Simon).

If admin Simon opens project settings, Users tab; then on a different computer owner Garfunkel transfers project ownership to Simon; then new owner Simon who still sees himself as just admin Simon removes himself from the project without refreshing the page, he is successful. Result: Garfunkel is a project admin and the project has no owner.

This is a ridiculous edge case, but it shows there could be some safeguard added in the backend to prevent project owner removal without replacement.

**Comment by jasonleenaylor** [comment]
Probably we should just throw an error from the backend if we remove an owner without replacing it.
