### ISSUE TITLE
Review Entries | Delete button does not work

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#312]
The delete button is not functional on this page.

<img width="938" alt="delete-bug" src="https://user-images.githubusercontent.com/10340167/81473506-f059e300-91cc-11ea-806f-5e8ec8b4f628.png">

**Comment by Rapdorian** [comment]
Seems to work fine when I tried it. You do have to hit the checkmark for your changes to take effect. Before that it just grays them out which it seems to be doing in your screenshot
