### ISSUE TITLE
Recording on two different entries back-to-back is broken

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#3151]
**Describe the bug**

In the Review Entries tool, if you record audio for one entry, then try to record on a different one without first clicking elsewhere, either a second glitch recording appears on the first or 400 error occurs, such as
```
400 https://thecombine.app/v1/projects/626163298f13d53c418181ff/words/665f68e5bb6b4afb1ea21f1d/audio/upload
```

This is probably an unintended consequence of #3077, which was tested in Data Entry, but clearly not enough in Review Entries. 

**To Reproduce**

1. Open a project with at least two words.
2. Click on Data Cleanup > Review Entries
3. Click-and-hold the record icon (red circle) for one row
4. When you release, a new play icon (green triangle) should appear in that row
5. Click-and-hold the record icon in a different row
6. Observe bug

**Comment by jmgrady** [comment]
This looks like the same root cause as #1930.

**Comment by imnasnainaec** [comment]
> This looks like the same root cause as #1930.
> 
> See [axios/axios#4406](https://github.com/axios/axios/issues/4406) for some possible solutions.

They can both result in a 400 error, but they look much different to me. This one doesn't prevent audio recording in general. Just the specific case of back to back recordings on different rows of Review Entries.
