### ISSUE TITLE
Projects not shown in ProjectScreen list until the user logouts / logs back in

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#316]
The issue is that `backend.getAllProjectsByUser` bases the project list off of the JWT token stored in local storage. This means that a user's list of projects won't be updated until they log out and log back in. So if they back up to the `ProjectScreen` the list won't show project's they've made since they logged in.

**Comment by johnthagen** [comment]
Part of the issue is that `backend.getAllProjectsByUser` bases the project list off of the JWT token stored in local storage. This means that a user's list of projects won't be updated until they log out and log back in. So if they back up to the `ProjectScreen` the list won't show project's they've made since they logged in.

**Comment by stevendyk** [comment]
From 05/26 Requirements: Users need to see which projects they are part of, and currently on.
