### ISSUE TITLE
Can play multiple recordings simultaneously

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#330]
This has been tested in Ubuntu 18.04 on Firefox and Chromium and in Windows 10 on Chrome and Firefox.

In both Data Entry and Review Entries, multiple recordings (for the same entry or different entries) can be played simultaneously. You can even add a new recording while another recording is playing. It would be good to have the press of a play or record button cut off any active playback.

**Comment by stevendyk** [comment]
Related to issue #485
