### ISSUE TITLE
In Review Entries, can only add one new recording per entry without refreshing the page.

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#331]
This has been tested in Ubuntu 18.04 on Firefox and Chromium and in Windows 10 on Chrome and Firefox.

In the Review Entries page (https://thecombine.languagetechnology.org/goals/8), you can add a new recording to a page, but have to refresh before you can add another recording to the same entry. Resizing the page, editing entries, or adding a recording to another entry are not sufficient to allow a second recording for an entry. 

This may be related to https://github.com/sillsdev/TheCombine/issues/328, another bug that manifests after a recording but is fixed by a refresh.

**Comment by stevendyk** [comment]
Related to issue #485
