### ISSUE TITLE
Create initial database admin on target systems

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#344]
The playbooks that install the combine on the demo server and the NUCs need to create an initial, known database user with admin privileges.  Requirements:
1. When TheCombine is first started, there shall be a user, `admin`, pre-installed in the database;
2. The `admin` user shall have the same password across all systems;
3. The `admin` password shall be encrypted in the github repo (e.g. stored in an Ansible vault variable or file)

**Comment by johnthagen** [comment]
Relates to #305

**Comment by jmgrady** [comment]
John (@johnthagen), Jason (@jasonleenaylor),
I would like your thoughts on this topic.  I have thought of two methods to solve this problem:
1. Create an executable that can be run on the target system that creates/updates an admin user.
   In order to do things the ansible way, I would want the executable to return an exit code that indicates "No change", "Successful change", or "Failure".
2. Have the backend create the user at first start (it already creates the database, I believe).
   In this case, we could create environment variables for the backend process that tells it what username/password to use.  I don't think that we will want to worry about multiple users being created or for non-admin users to be created.  If I understand correctly, the main purpose here is to have an admin user defined who can be used to make other users admins if needed.

I have not delved into the password hashing code very deeply but if it is equivalent to one of the methods described [here](https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module) then the ansible playbook can generate the password field and use the mongo shell to create the user as needed.

I'm sure that there are other ways to solve this as well.  Let me know your ideas.

**Comment by johnthagen** [comment]
The password hashing algorithm is defined here:

https://github.com/sillsdev/TheCombine/blob/b3cfd3623c158036f2d73bb9a133b76baafdd44e/Backend/Services/UserApiServices.cs#L34-L66

And duplicated here:

https://github.com/sillsdev/TheCombine/blob/b3cfd3623c158036f2d73bb9a133b76baafdd44e/Backend/Services/UserApiServices.cs#L158-L190

At a minimum this logic needs to be consolidated in the backend, so I'll work on that.

@jasonleenaylor How have you handled this in the past on other .NET Core applications?

The frameworks I'm most familiar (Python/Django) provides a [`createsuperuser`](https://docs.djangoproject.com/en/3.0/ref/django-admin/#createsuperuser) command line management command for this.

**Comment by jmgrady** [comment]
@johnthagen 
An executable like the createsuperuser in Python/Django was what I had in mind for option 1.  I had seen the logic in the backend - I missed that it was in 2 places and I certainly don't want to create a third! ;-)
In thinking the Ansible way, I would like to be able to tell the difference between:
- nothing changed, i.e. admin user existed and the password is the same
- something changed and it worked, e.g. admin user created, or password updated
- did not work
The reason for this is that one might want to trigger a task, such as restart a service, if it changes but leave it alone if it did not.  Right now, I cannot imagine a task that needs to run on a change but I would not want to select an interface that cannot be extended to allow it in the future.  I would rather not look for key words in stdout or stderr since that is more likely to change over time.

As far as managing the PRs, either we can separate the changes into 2 PRs or we can create an integration branch where you can deliver changes to the Backend and I can update the Ansible scripts.  In this case, you can deliver your changes without the Ansible changes so either way works for me.

**Comment by johnthagen** [comment]
I'm doing some research on how to best do this.

**Comment by jmgrady** [comment]
Thanks, John.  One thought I had was to put the password generation into a separate object whose source code could be shared between two executables.  We currently install node in the target although we haven't needed it until now, possibly.  Or, the Ansible scripts could call the second executable with node and use the mongo shell to create the record passing in the password fields.  We'll see at 3:30 how Docker might affect any of this.

⁣Jim

"In practice, the difference between theory and practice is greater than it is in theory."​

**Comment by johnthagen** [comment]
I'm currently exploring just adding an optional command line parameter to the backend. Something like `dotnet run create-admin-name=admin` and pass the password in as an ENV variable. That's how I've seen this done in other frameworks, and I think it should work.

That way all of the code is reused in the backend. We'll see how my prototype goes.
