### ISSUE TITLE
Create administrative login on NUC targets

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#345]
The playbooks that install the combine on the NUCs need to create an initial, known login with `sudo` privileges. Requirements:

1. `playbook_nuc.yml` shall create a login user, `admin`;
1. The admin user shall have the same password across all systems;
1. The admin password shall be encrypted in the github repo (e.g. stored in an Ansible vault variable or file)

**Comment by johnthagen** [comment]
> The admin password shall be encrypted in the github repo (e.g. stored in an Ansible vault variable or file)

I've also seen environment variables used for this so that the password isn't saved in the repo at all. Perhaps we should put and environment variable into our TeamCity build for this?

There are already other secret environment variables set in our TeamCity build, such as `JWT_KEY`. See https://build.palaso.org/admin/editBuildParams.html?id=buildType:TheCombineUnitTests

**Comment by jmgrady** [comment]
This will only be needed in the TeamCity build to the extent that the unit tests need to verify any specific backend behavior, for example, if the first time the backend is started it automatically creates the admin user and uses an environment variable for the password, then there should be unit tests to verify this behavior and the environment variable will be needed.  (I am only writing this as an example, not necessarily proposing it as the best solution.)

Even so, note that even if a value is specified by an environment variable, it still needs to go into the repo so that the installation process can build file that creates and launches the backend service.  This is where the Ansible vault comes to the rescue.  We can store the value password  as an ansible variable but have it in a file that is encrypted.  When Ansible runs the playbook to install/maintain the software, it prompts you for the vault password so that it can be decrypted.  This password is not posted in the repo and is not in the README.md files.  I listed this as a requirement so that we don't forget to verify this.
