### ISSUE TITLE
When word and gloss are entered and complete is clicked it should act as if enter had been pressed

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#355]
If the user clicks the complete button before hitting enter the data is not saved and the user is not notified.

We will now act as if the user has clicked enter when there is data in the new entry fields and complete is clicked.

 [5/26 Requirements #15](https://docs.google.com/document/d/1A9Wv7SY_peIqdfGEBgzdl-7Pn19Dn70CDy9apVOUiak/edit#heading=h.29952ofgcdh)

**Comment by stevendyk** [comment]
From 5/26 Requirements #17: If the user enters a word and a gloss in the data-entry boxes but doesn’t press Enter, when s/he **clicks on Complete, that entry and gloss should be saved as part of the list of words in that domain.** We think this is what happened to Verna in the above scenario

**Comment by imnasnainaec** [comment]
Resolved.
