### ISSUE TITLE
AutoComplete errors when clicking on 'New Sense' 

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#358]
[5/26 Requirements #19](https://docs.google.com/document/d/1A9Wv7SY_peIqdfGEBgzdl-7Pn19Dn70CDy9apVOUiak/edit#heading=h.sefaez1m12o)

[Steve] I am not sure if this is one issue, or illustrates several UX issues with selecting an edit option.

**Comment by jasonleenaylor** [comment]
Clicking on Add New Sense has the immediate effect of adding the current data as a new sense of the item offered by AutoComplete.

If the user hasn't added a Gloss yet it adds a new sense with an empty gloss. This is never what the user wants. 

Development Task:
As a first step we should disable the Add New Sense button until the gloss is filled in.

If this doesn't lead to the user discovering what they need to do we will add further UX changes later.
