### ISSUE TITLE
No way to log off unless in 

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#363]
5/26 Requirements #26: BB: When I was finished, I couldn’t figure out how to get to where I could log off.  I hit “Complete” to get out of data entry mode.  Then I was at the tree.  I couldn’t see any way to get out.  I agree with Verna and Kevin that it is counter intuitive to have to go back into data entry mode to get the tabs at the top for “Data Entry” and “Data Cleanup”, and to have the logout option.

**Comment by johnthagen** [comment]
I think having the top app bar always present (I think addressed in #353) would really help with this and make the app overall a lot easier to use.

**Comment by imnasnainaec** [comment]
It seems the use of `fullscreen` makes the TreeViewComponent cover everything else: https://github.com/sillsdev/TheCombine/blob/master/src/components/DataEntry/DataEntryComponent.tsx#L67
