### ISSUE TITLE
Invite to project - Frontend Component

### ISSUE THREAD

**Issue by jasonleenaylor** [sillsdev/TheCombine#382]
The current method of clicking on the listed users needs to be removed and replaced by a new component labelled 'Add Users'.

The new component should have 2 parts.
A list that has a search which will match either name or email and an button that adds the user to the project.
A form that takes an e-mail address and has an 'Invite' button which will call a method on the backend to send the e-mail.

The list should be blank initially and only fill with suggestions after 3 characters are entered
Adding a user from the list should call the same backend methods that clicking on the user in the current control does.

The invite form should use an e-mail validator.

There are two other issues required to complete this feature.

**Comment by jmgrady** [comment]
Should the invitation form be greyed out when there is no internet access, e.g. when using the NUC in a remote area, or is the use model more that people are invited to join the project after the workshop during Data Cleanup?
It should be more than whether it's a NUC or the public server.  The NUC can act as a router from its WiFi access point to its wired connection.

**Comment by jmgrady** [comment]
On second thought, the NUC may not be accessible even when on a wired network - unless part of the setup of each NUC is to get a reserved DHCP address on the SIL Intranet.  [Right now, the NUC at SIL in Dallas is reachable as `anglophone` when connected to the SIL Intranet.]
