### ISSUE TITLE
Be able to delete projects

### ISSUE THREAD

**Issue by shyung18** [sillsdev/TheCombine#402]

**Comment by imnasnainaec** [comment]
Administrative users can delete a project with #464

**Comment by imnasnainaec** [comment]
This issue remains open because non-administrative project owners should (perhaps) be able to delete their own projects.

**Comment by imnasnainaec** [comment]
The site admin can permanently delete projects as of #1031.

**Comment by imnasnainaec** [comment]
And project owners can archive their project in the Project Settings.
