### ISSUE TITLE
Word stack does not merge into top card

### ISSUE THREAD

**Issue by SamDelaney** [sillsdev/TheCombine#42]
Not positive, but it appears this way.

**Comment by Rapdorian** [comment]
Fixed

**Comment by SamDelaney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dragging with background selected shows entire background being dragged. #43](https://trello.com/c/CQXigtvP/98-dragging-with-background-selected-shows-entire-background-being-dragged-43)
