### ISSUE TITLE
Dragging with background selected shows entire background being dragged.

### ISSUE THREAD

**Issue by SamDelaney** [sillsdev/TheCombine#43]
Can either: 
Prevent background from being selected
Only show the dragged card

**Comment by Rapdorian** [comment]
Elaborate?

**Comment by SamDelaney** [comment]
Issue with using browser default drag-and-drop. Behavior changes based on browser.

**Comment by SamDelaney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dragging with background selected shows entire background being dragged. #43](https://trello.com/c/CQXigtvP/98-dragging-with-background-selected-shows-entire-background-being-dragged-43)
