### ISSUE TITLE
Make Goal Router and User edits work together

### ISSUE THREAD

**Issue by Rapdorian** [sillsdev/TheCombine#456]
Right now the goal router sources all of it's data from the redux store. Goals are never properly stored in the backend in any way. The closest we get is the UserEdits collection, which currently is filled with mostly empty data. I think we should completely abandon storing our goals in the redux store and instead have the goal router fetch data from the backend.

- [ ] Change UserEdits to store a single goal
- [ ] Store goal data in UserEdits
- [ ] Fetch goal data from user edits in GoalRouter

**Comment by imnasnainaec** [comment]
We are expanding backend User Edits as needed to store any frontend Goal properties that need to persist.
