### ISSUE TITLE
Disallow editing completed goals

### ISSUE THREAD

**Issue by Rapdorian** [sillsdev/TheCombine#457]
After #456 is implemented it will introduce some undefined/buggy behaviour when you try to access a goal that has already been completed. Technically the bug exists before #456 but it is harder to reliably access a past goal. We need to add a field to goals concerning if they have been completed. This field will likely actually be on each step and checking if a goal is complete is just the sum of the steps. If you attempt to navigate to a completed goal/step it should display some kind of description of what was done.

**Comment by imnasnainaec** [comment]
Replaced by #931 and related work.
