### ISSUE TITLE
Allow navigating to specific steps

### ISSUE THREAD

**Issue by Rapdorian** [sillsdev/TheCombine#458]
Currently multistep goals like mergedups are broken because there is no way to navigate to a specific step within that goal. Since mergedups has 8 steps there are 8 different pages being served under `thecombine.app/goals/<goalid>`. This means the only difference between those 8 pages is browser state. This is the cause of #393. We should modify the GoalRouter so that it takes an additional URL paramter for the step number (`thecombine.app/goals/<goalid>/<stepid>`). The step id paramter should be optional for 1 step goals and will allow us to more precisely navigate multi step goals

**Comment by imnasnainaec** [comment]
We are moving more toward state and away from url-controlled goal status (cf #1107).
