### ISSUE TITLE
Add CI job that tests Docker Compose project

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#460]
We should add a CI job that ensures that our Docker Compose project builds.

The CI Runner would need *either*:

- Docker and the ability to run the [`dind`](https://hub.docker.com/_/docker) Docker image (Docker in Docker).

- Or, has Docker Engine and Docker Compose installed on the system and the following command can be run from a shell:

   ```bash
    $ docker-compose build
    ```

The return value will indicate if the build was successful or not.

**Comment by jmgrady** [comment]
TeamCity is now setup to build the Docker implementation and deploy it to the QA server when a PR is merged into `master`
