### ISSUE TITLE
UI for Add New Sense is cumbersome and counter-intuitive. (W, X)

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#478]
Related Issue: [#467](https://github.com/sillsdev/TheCombine/issues/467)

06/30 Testing Notes: [W: ](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.rjsmrncvnlon) [X: ](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.25ok25202zq7)

I want to make the data entry screen a fast and smooth way to add data while minimizing the amount of junk in the database. I agree with the testers that we should hide the decision of adding a new sense or word from the typist.

When the data entry tool tries to write a new entry to the database it will first check if the vernacular and gloss are already present in the database a good initial behaviour would be
```
if vern in db {
  if gloss in word {
    add semdom to sense
  } else {
    add send to word
  }
} else {
 add word to db
}
```
however it may also be good to have that behaviour configurable on a per project basis.

This will require the data entry tool to be smarter about editing fields that have already been written to the database. example: if it has already written a new sense to a word and you change the vernacular field it should know to remove the sense it added before adding a new sense/word somewhere else.

We should consider if we want to keep the current method of streaming entries to the database or if want to send them in batches with the complete button

**Comment by imnasnainaec** [comment]
Completed in #585
