### ISSUE TITLE
Autosuggest for Glosses should follow the switch for Vernacular in settings.

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#480]
06/30 Test Notes [K](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.kgo4shb3u144),[M](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.kvckt54zak8e),[R](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.d7kzzbiq5h57)

**Comment by Rapdorian** [comment]
Auto sugges for glosses is currently functionally broken in multiple ways. I will be picking an issue to turn into an overhaul of the gloss autosuggest and I will link the issue to that.
