### ISSUE TITLE
“Misspelled gloss” message persists even when the gloss is correct and has turned black.

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#481]
[06/30 Test Issues S: ](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.v9dvx46kr2) 
And: Gloss auto suggestions are lacking.
And: No suggestions for longer words when what has been typed is a (shorter) real word.

[T: ](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.x1sal853eokh) Messages persist even after data has been committed.

**Comment by Rapdorian** [comment]
Autosuggest for glosses is currently functionally broken from a design standpoint. I will be picking an issue to turn into an overhaul of the gloss autosuggest and I will link this issue to that.
