### ISSUE TITLE
UI for recording is unclear

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#485]
Related to issue #331 and #330 

[06/30 Test Notes GG](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.733cltd19da1)

**Comment by Rapdorian** [comment]
We should also look into when we are requesting microphone permisssions from the browser.

While I like the UI in review entries I am not sure it is all that clear. I think adding a microphone icon would make it easier to read.
I also think the color change in review entries may be too subtle. I think something like the following might work.
![data_entry_recording_off](https://user-images.githubusercontent.com/7032450/86636344-2aafe880-bfa2-11ea-8141-eb30a3af0767.png)
![data_entry_recording_on](https://user-images.githubusercontent.com/7032450/86636349-2be11580-bfa2-11ea-9eb1-521a9c631bbd.png)


I am not sure if we want to allow multiple recording in the data entry component so I have attached two examples of what the screen might look like after recording.
![data_entry_recording_finished_allow_single](https://user-images.githubusercontent.com/7032450/86636408-3ef3e580-bfa2-11ea-8889-d43d55333c65.png)

With allowing multiple recordings I think the shift+click method of deleting is rather confusing and can be improved with a small icon.
![data_entry_recording_finished_allow_multiple](https://user-images.githubusercontent.com/7032450/86636405-3d2a2200-bfa2-11ea-9d29-edded98a5867.png)
