### ISSUE TITLE
Add (display) semantic domain info to UI

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#491]
Related issue #338 
06/30 Test Notes [(BB)](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.95hrijq6sgj6)

[Trello card](https://trello.com/c/RDuITN6s/276-add-semantic-domain-info-to-ui), James' Note: Like I mentioned for the gloss I think we should pivot to a autocompletion style for this that can be navigated with arrowkeys. The semantic domains can be added to those entries

**Comment by imnasnainaec** [comment]
Resolved by #585
