### ISSUE TITLE
Keep track of who enters what data

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#492]
06/30 Test Notes [(G)](https://docs.google.com/document/d/1krZBYHaO9lG1Sry59K5PZPvvMoRCt7ttKe9SWYV5qUI/edit#heading=h.aqkwsrzajmbi)

**Comment by imnasnainaec** [comment]
This should involve a unified refactor of both `UserEdits` and `Word.editedBy` and their uses.

**Comment by imnasnainaec** [comment]
Related: #1873
