### ISSUE TITLE
Vernacular Autocompletion

### ISSUE THREAD

**Issue by Rapdorian** [sillsdev/TheCombine#494]
![2020-07-06-161024_3840x1080_scrot](https://user-images.githubusercontent.com/7032450/86637179-259f6900-bfa3-11ea-8a50-2ac79f860c7f.png)
The current autocompletion for vernaculars is very large and extends many times the height of the textbox down the page. The auto completion also is nearly impossible to operate with the keyboard.

I think it would be beneficial to stop trying to reinvent the wheel with autocompletion and do something like the following
![data_entry_vern_suggest](https://user-images.githubusercontent.com/7032450/86637301-4e276300-bfa3-11ea-88ef-b03811f0c7ed.png)
It is a far more compact solution that is easier to read and should solve most of our problems with keeping it onscreen. We should also be able to use [Material UI's Autocomplete component](https://material-ui.com/components/autocomplete/) to implement it without much trouble. This component seems to have a way to change the rendered list items so we can make the custom display with glosses and semantic domains.

Hopefully this would remove the need for #484

**Comment by stevendyk** [comment]
[Testing Notes 7/10/2020, Vernacular autocomplete options (similar words) are not always all visible](https://docs.google.com/document/d/1njDXI6dkj8G1vJMoxdpFWwNGwJz_RklWS5AdC07_AcI/edit#heading=h.h8xlfpgurhyb)
