### ISSUE TITLE
Investigate if email reset needs DOS protection

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#499]
We currently don't have any limits in how fast the password resets can be sent. A malicious actor might be able to flood our STMP server (and users) with password resets. I imagine most email providers would stop such things, but I don't know the ramifications on the reputation of our STMP server then (would GMail start blocking all mail from our domain?).

Might be something to look into.

Related to #445

**Comment by StevesBro** [comment]
The email is included in the backend call: https://localhost:5001/v1/users/checkemail/{email}.
This should be changed.

**Comment by jasonleenaylor** [comment]
Cloudflare has this covered for us.
