### ISSUE TITLE
"Domain" Button bounces on Data Entry

### ISSUE THREAD

**Issue by shyung18** [sillsdev/TheCombine#502]
The bounce animation is added to the domain buttons, but the disabled "Domain" button at the beginning of the data entry also bounces which we don't want. 
Tried this:
`{this.props.currentDomain.parentDomain ? (
              <Bounce ...
            ) : (
              <Button
                fullWidth
                ...
              >`
But this doesn't put the bounce effect on the next semantic domain chosen. It works for all the other ones though.

**Comment by imnasnainaec** [comment]
This issue will likely become irrelevant due to #684
