### ISSUE TITLE
If the “Vernacular” box is cleared there should be no AutoComplete options

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#531]
[Testing Notes 7/10/2020 , Empty “Vernacular” box displays “similar words”](https://docs.google.com/document/d/1njDXI6dkj8G1vJMoxdpFWwNGwJz_RklWS5AdC07_AcI/edit#heading=h.2z4omimulm9b)

**Comment by jasonleenaylor** [comment]
We are changing the AutoComplete feature now, but when it is complete we should make sure that after typing some characters and clearing them we also stop showing autocomplete when the last character is removed.
