### ISSUE TITLE
Allow user to see Entire Font Characters

### ISSUE THREAD

**Issue by 14JAW** [sillsdev/TheCombine#549]
For some Characters, the current display will cut off part of the bottom or something to where it does not look like the character we desire.

**Comment by imnasnainaec** [comment]
Test word: g̱wa̱g̱wax̱wa̱lał

**Comment by imnasnainaec** [comment]
`TextField` cuts off diacritics below tails. Issue submitted: https://github.com/mui-org/material-ui/issues/22104

**Comment by imnasnainaec** [comment]
Was only partially fixed by #560.

**Comment by imnasnainaec** [comment]
A taller text field has been merged into material-ui for future release: https://github.com/mui-org/material-ui/pull/22149

**Comment by imnasnainaec** [comment]
It is in an alpha release: https://github.com/mui-org/material-ui/releases/tag/v5.0.0-alpha.7
