### ISSUE TITLE
Audio: no feedback for recording success or failure

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#564]
#362 failed user test. 
Please add a "playback" arrow. That will do two things at the same time: 

1. reassure the user that a recording was made, 
2. provide a means to evaluate the quality of the recording that was made. 

See [7/31 #5.](https://docs.google.com/document/d/1kUIPMw1SHWXeP6q32QNhxCT0P8RHFSSb7IyclOtvUFI/edit#heading=h.n8rm907taah6)

**Comment by imnasnainaec** [comment]
I believe this was fixed in #551 , which didn't make it into last weeks release.
