### ISSUE TITLE
In Review Entries, can only add one new recording per entry without refreshing the page

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#565]
#331 Failed user test. Related: #439 #466 
Reference [7/31 #6.](https://docs.google.com/document/d/1kUIPMw1SHWXeP6q32QNhxCT0P8RHFSSb7IyclOtvUFI/edit#)

**Comment by imnasnainaec** [comment]
Unable to replicate this bug at https://thecombine.languagetechnology.org.

**Comment by stevendyk** [comment]
[Kevin Warfel] I tested this again just now, and I was able to make multiple recordings without refreshing the page.
