### ISSUE TITLE
Stop docker containers before updating

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#568]
Sometimes when updating the docker containers while they are running, the frontend container restarts continuously.  Update the Ansible scripts to detect if the docker containers are running and stop them before building and starting the new containers.

**Comment by johnthagen** [comment]
This shouldn't be necessary and I think that the `staticfloat/nginx-certbot` has so other kind of issue going on. I've run a lot of production Docker Compose installs/upgrades and reinstalling an image while a container is running has never caused issues like this.

I think we need to take a closer look at at what the `staticfloat/nginx-certbot` scripts are doing to figure out why it's halting when we aren't using certbot. It could be a race condition based on when it detects the backend's hostname (`backend`) as defined in `docker-compose.yml` or something else. The base `nginx` image did not have this problem so I'm thinking that there is some extra complexity we need to understand about `staticfloat/nginx-certbot` starts up.

**Comment by jmgrady** [comment]
On further investigation, I agree with John's comment.  This should not be necessary.  I have created issue #696 for this and am closing this issue.
