### ISSUE TITLE
Choosing a suggested spelling option for Gloss does not place the focus back in the Glosses box

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#571]
#486, #495 did not pass user tests. 
Reference [07/31 Testing Notes 7](https://docs.google.com/document/d/1kUIPMw1SHWXeP6q32QNhxCT0P8RHFSSb7IyclOtvUFI/edit#)

**Comment by imnasnainaec** [comment]
Does this refer to choosing a gloss suggestion on ExistingEntry or NewEntry?
Also, there are multiple ways to select an option: click on the option, press enter, or move focus elsewhere (via tab or clicking elsewhere). Which is in view here?

**Comment by imnasnainaec** [comment]
This behavior should be fixed when we refactor/replace the current ImmutableEntry structure.

**Comment by imnasnainaec** [comment]
This is subsumed into #608
