### ISSUE TITLE
Frontend exception thrown when trying to merge duplicates after a single entry is inserted

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#588]
To reproduce:

1. Register a new user
2. Login
3. Create a new project
    - Test
    - French
    - English
4. Data Entry
5. Domain: Hot
6. Add entry
7. Add audio clip
8. Complete
9. Data Cleanup
10. Merge Duplicates

Error:

<img width="773" alt="frontend_crash" src="https://user-images.githubusercontent.com/10340167/90250726-86c02500-de0a-11ea-87df-1fd4186479c1.png">

**Comment by johnthagen** [comment]
Also, each time I hit Merge Duplicates in this state, the URL keeps changing and incrementing?

http://localhost:3000/goals/5
http://localhost:3000/goals/6
http://localhost:3000/goals/7
http://localhost:3000/goals/8

...

Not sure if that is expected either.

**Comment by johnthagen** [comment]
In recommendations page, there is then a very long list of "Merge Duplicates" under "You've completed". Perhaps this is to be expected, but just wanted to note it in case it was related.

<img width="932" alt="completed" src="https://user-images.githubusercontent.com/10340167/90252295-35fdfb80-de0d-11ea-89e1-42c38d0d1ee0.png">

**Comment by imnasnainaec** [comment]
Likely related: #243 #795
