### ISSUE TITLE
User "Name" not stored after creating a new user

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#589]
1. Register a new user
<img width="329" alt="bat_register" src="https://user-images.githubusercontent.com/10340167/90251030-182f9700-de0b-11ea-8371-1b5d3ac4cebd.png">

2. Log in

3. Open User Settings

4. Note missing User Name (should Bruce Wayne be populated here?):

<img width="329" alt="bat_settings" src="https://user-images.githubusercontent.com/10340167/90251115-385f5600-de0b-11ea-9908-c6c4b7325b98.png">

**Comment by jmgrady** [comment]
I just looked at my user settings on the live server.  I looks like the Name is being populated with the phone number.
![image](https://user-images.githubusercontent.com/10785548/90278192-fe0aae80-de34-11ea-9318-cbfa04ed2d63.png)

**Comment by johnthagen** [comment]
This is simple enough that I'll go ahead and fix it.
