### ISSUE TITLE
Projects created before pr #618 should probably have autocompleteSetting updated

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#612]
Pull request #618 changes the options and default for the autocompleteSetting property, so _after that merges into master_ we should probably set all projects to the new default with the following command:
`mongo -eval "db.getSiblingDB('CombineDatabase').getCollection('ProjectsCollection').update({}, {\$set: {'autocompleteSetting': 'On'}}, {multi: true})"`

**Comment by imnasnainaec** [comment]
@jmgrady #618 is merged into `master`

**Comment by jmgrady** [comment]
Done.

**Comment by imnasnainaec** [comment]
Added to [MongoDB 1-time maintenance scripts](https://docs.google.com/document/d/1L9WjBZqBNVfxk5KiIQo5Fzjsetv4JuwGU0wuYKDRtWo)
