### ISSUE TITLE
Put the media files into separate pronunciation fields.

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#623]
Request: Place each audio file in a separate Pronunciation group, so that we can choose to publish the pronunciations in different publications.

Kevin: 
> I did some recordings in The Combine, then exported the project and imported it into a FLEx project. There I observed that they end up in the Media File field in the Pronunciation group. Furthermore, if there are multiple recordings for the same entry, they are grouped within a single Pronunciation group, rather than each Media File being assigned to a separate Pronunciation group. (See first screen shot below.)

> Verna had also asked me to do a test upload to Webonary to make sure that the audio files work there. In the test I ran, the audio icons are there in the entry on Webonary, but they appear to be grayed out, and clicking on them produces no sound. (See image 2 below, where the red line is my addition to the screen shot.) So there is some concern on our end that the format of the recordings done in The Combine may not be compatible with Webonary.

Steve: the following is in the same test report / email from Kevin, and has already been resolved. 
Kevin: 
> In the test I ran, the audio icons are there in the entry on Webonary, but they appear to be grayed out, and clicking on them produces no sound. 

Jason: 
> I have already fixed FieldWorks to consider the media type used by 'The Combine' to be acceptable to webonary. That change will be present in the upcoming stable.

![image003](https://user-images.githubusercontent.com/25255423/90791289-a35ad200-e2ce-11ea-996d-7a007ccb5651.jpg)
![image007](https://user-images.githubusercontent.com/25255423/90791802-49a6d780-e2cf-11ea-9514-9083c64e4a7d.png)

**Comment by imnasnainaec** [comment]
It's not clear whether the default should be separate pronunciations or (as it currently is) multiple files in the same pronunciation. From discussion with Kevin, we've concluded to leave as is until we hear that it should change.
