### ISSUE TITLE
Backend Tests need file cleanup

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#656]
Every time `dotnet test Backend.Tests/Backend.Tests.csproj` is run, it leaves ~16 folders in `.CombineFiles/`. Since that folder is also used for project data, we can't just delete the whole folder (as had been done before #655). Some sort of cleanup is needed to prevent those test folders from accumulating on the developers.

After running Backend tests once:
![image](https://user-images.githubusercontent.com/6411521/91456062-d3671f80-e850-11ea-9924-0027de9b5894.png)

After running a second time:
![image](https://user-images.githubusercontent.com/6411521/91456315-1e813280-e851-11ea-8ee4-180f31e5ca19.png)

**Comment by johnthagen** [comment]
When I run the backend tests locally, it creates

- 45MB worth of data
- 17 Top level folders
- 101 folders
- 82 files

**Comment by johnthagen** [comment]
Related: #789
