### ISSUE TITLE
On creation of new project, the userRole created for the project is added to the user but not persisting

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#692]
Creating a new project successfully creates a new userRole and applies that to the user (https://github.com/sillsdev/TheCombine/blob/master/Backend/Controllers/ProjectController.cs#L133-L135). A debugging run showed the new userRole present at the end of that controller function. Once the project is created, userEdits are setup for the project (https://github.com/sillsdev/TheCombine/blob/master/src/components/ProjectScreen/CreateProject/CreateProjectActions.tsx#L75) which may update the user overwriting the userRole just added (https://github.com/sillsdev/TheCombine/blob/1cbc32cff95473095365741619daccc5a1b834f9/src/components/GoalTimeline/GoalsActions.tsx#L82-L96).

**Comment by imnasnainaec** [comment]
I think this is the culprit: getting the user from localStorage instead of the backend (https://github.com/sillsdev/TheCombine/blob/1cbc32cff95473095365741619daccc5a1b834f9/src/components/GoalTimeline/GoalsActions.tsx#L203-L211) then making an update in the backend with that (https://github.com/sillsdev/TheCombine/blob/1cbc32cff95473095365741619daccc5a1b834f9/src/components/GoalTimeline/GoalsActions.tsx#L73-L74)

**Comment by johnthagen** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

Classic cache invalidation challenge.
