### ISSUE TITLE
Console shows an error when the frontend requests an avatar for a user that hasn't uploaded one

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#697]
This is particularly an issue in ProjectSettings and SiteSettings where the list of all users is fetched.

**Comment by johnthagen** [comment]
Yeah, I've seen this too, and I agree it would be better for the frontend to know if a user has an avatar or not based on the User model, and only try to fetch the image if it exists.

The 404s from the invalid avatar fetching can mask other issues.
