### ISSUE TITLE
Add username next to avatar in the AppBar

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#699]
We probably want the username to show up only when the window is sufficiently wide.

**Comment by asharonbaltazar** [comment]
Hello, I feel like this is something I can work on. Can you please provide me with some more details? Perhaps a screenshot?

Thank you.

**Comment by imnasnainaec** [comment]
@asharonbaltazar All development on TheCombine begins with successfully [installing and running everything](https://github.com/sillsdev/TheCombine#getting-started-with-development).
