### ISSUE TITLE
Developers could benefit from commands for running tests and coverage on specific folder

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#704]
Testing and coverage available according to our README:

`npm run coverage`
* This can take a few minutes, so it would be nice to be able to run this on specific files or folders

`npm test` or `npm run test`
* This also runs `dotnet test Backend.Tests/Backend.Tests.csproj` which slows down the work of somebody just wanting to run frontend tests; maybe something like `npm run test frontend` and `npm run test backend` could be added for just one or the other
* You can add a string at the end of the command (e.g. `npm test DataEntry`) and it will only run test files with that string in the path (frontend--all backend tests still run); this should be added to the documentation. Is there an analogous method for the backend testing?

**Comment by johnthagen** [comment]
I agree that the frontend and backend test running scripts should be separated.

**Comment by johnthagen** [comment]
This will also require coordinated TeamCity CI configuration updates.

**Comment by johnthagen** [comment]
@imnasnainaec Does VSCode support the equivalent of this in the IDE?

<img width="814" alt="rider_test" src="https://user-images.githubusercontent.com/10340167/94271224-51c9e680-ff0f-11ea-93ac-b513f720bc09.png">

In JetBrains Rider, you can click on the little green arrow on the left side of a specific test to only run that specific test.
