### ISSUE TITLE
[ProjectSettings] See user roles in ActiveUsers list

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#705]
There is a list of users on the project, but no indication of their roles within the project.

The current display shows a list of users in the format: Name (username | email@address)
<img width="532" alt="Screenshot 2023-03-17 at 15 23 53" src="https://user-images.githubusercontent.com/6411521/226000543-c3bb8096-7b6e-4850-bd80-b3752d8fae18.png">

You can only determine whether they are a project admin or a project owner by interacting with the vertical three dots on the right. To make it more obvious, some small "admin"/"owner"/"editor"/"harvester" badge should be added next to the relevant users (either before the name or after the end parenthesis).

Work on this should wait until #2336 is done.

**Comment by Noothan-am** [comment]
hi @imnasnainaec is this issue still open. if yes, can you please share more information about this issue?
