### ISSUE TITLE
Allow users to change interface language

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#706]
The languages available for TheCombine ui are English, Spanish, and French, determined automatically depending on the browser language setting: "es" for Spanish, "fr" for French, anything else for English. So, e.g., if somebody's browser is set to Spanish - Mexico (es-mx), it will default to English. It would be nice to give the user one of the follow abilities: 
* switch languages (in the user setting) 
* switch the default language (in user settings or project settings)
* allow the analysis language--instead of the browser language--to determine the ui language  (in project settings)

**Comment by MattGyverLee** [comment]
Hi all. This would be helpful, but it's good to have a workaround of setting the browser language.

**Comment by MattGyverLee** [comment]
The feature of following the browser language seems to have been broken since the last time I looked at this post.

**Comment by jasonleenaylor** [comment]
Add UI language as a user setting.
