### ISSUE TITLE
Localization translations need updating

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#709]
We need to sync up `src/resources/translations.json` with [CrowdIn](https://crowdin.com/project/the-combine).
- [x] ->  There are new phrases that need translations
- [x] <- There are translations that need to be put into TheCombine

**Comment by imnasnainaec** [comment]
It also seems we aren't far from being able to expand the available languages (English, Spanish, French) to include Portuguese, Arabic, and Khmer.

**Comment by imnasnainaec** [comment]
Related: #706

**Comment by imnasnainaec** [comment]
The phrases in Crowdin were just updated, so all the languages that had 100% translation (Arabic, Azerbaijani, Chinese Simplified, French, Portuguese, Russian, Spanish) are now down to 50%.

**Comment by jasonleenaylor** [comment]
This process is underway and has become more regular
