### ISSUE TITLE
Add Notes field to Word

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#755]
### Backend

- [x] Extend `Word` `Model` to support saving a `string` note field in addition to the note's language (bcp-47 code `string`).
- [ ] Round trip the note content with the Lift import & export.

### Frontend

- [x] Extend `Word` and `ReviewEntriewWord` to support a note field.
- [x] Do not expose selecting the note's language, instead default to the project's current analysis language.
- [x] In Review Entries, add a note column, where notes can be added, viewed, edited.

**Comment by johnthagen** [comment]
An example note from FieldWorks:

```xml
<note>
<form lang="en"><text>Note in English</text></form>
</note>
```

**Comment by imnasnainaec** [comment]
Note support in Lift import & export still needed.

**Comment by johnthagen** [comment]
I can work on Lift import/export Friday if that is not too late. Happy to defer to @jasonleenaylor if he wants to pick it up.

**Comment by johnthagen** [comment]
Lift import of Words happens here:

https://github.com/sillsdev/TheCombine/blob/bdb341f41384d96760ae33696c188f43fada9586/Backend/Controllers/LiftController.cs#L166

**Comment by johnthagen** [comment]
Lift import logic implemented in `LiftMerger` class:

https://github.com/sillsdev/TheCombine/blob/bdb341f41384d96760ae33696c188f43fada9586/Backend/Services/LiftApiServices.cs#L408

**Comment by johnthagen** [comment]
Note contents are parsed and presented in this method:

https://github.com/sillsdev/TheCombine/blob/bdb341f41384d96760ae33696c188f43fada9586/Backend/Services/LiftApiServices.cs#L665
