### ISSUE TITLE
Refactor file storage paths

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#789]
There are many duplicated magic strings related to where files are stored in the backend. Search for the following terms to see the duplicates:

- `.CombineFiles`
- `ExtractedLocation`

Further, the current solution seems to mix temporary files (such as those used during Lift import and export) and permanent files, such as audio into the same directories, which makes it more difficult to prune temporary directories (#786) and can lead to strange edge-case bugs (#788).

It would be best to use `/tmp` file locations as much as possible.

**Comment by jmgrady** [comment]
Similar to making it difficult to prune temporary files, it makes it difficult to create efficient backups.  The current backup (as a compressed tarball) is 2.8 GB.

**Comment by johnthagen** [comment]
I'll plan to work on this Friday.

**Comment by johnthagen** [comment]
@jmgrady Going forward, the backups of new projects should not have any extraneous files in `.CombineFiles`.
