### ISSUE TITLE
Note field Lang = ""

### ISSUE THREAD

**Issue by SaraMeiSL** [sillsdev/TheCombine#806]
The language code is not set in the Note field, it is just left empty. As a result, when the LIFT file is imported into FieldWorks, a second analysis language is created as the language is not known. 

Suggestion - set the note field language to be the same language code as the gloss language. 

![image](https://user-images.githubusercontent.com/74278075/98755728-01eb9580-237e-11eb-9172-ae0e1824cf23.png)

**Comment by imnasnainaec** [comment]
Currently, the project's analysis language is assigned to the note on any new entry (in `addNewWord()`: https://github.com/sillsdev/TheCombine/blob/master/src/components/DataEntry/DataEntryTable/DataEntryTable.tsx#L152). But you are right that entries created before notes were enabled in The Combine will have `language=""`.

**Comment by SaraMeiSL** [comment]
ok, thanks for the update! Seems that future new entries will be fine, so that's enough.
