### ISSUE TITLE
Configure backend COMBINE_CORS_ORIGIN

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#825]
#817 introduced Web Sockets, which forced us to roll back the "Allow Any" CORS rules we currently had the on the backend.

As a result, for non-NGINX/Docker based deployment, we will need to configure the backend via the `COMBINE_CORS_ORIGIN` environment variable so that clients can make requests directly to the backend in production environments. This value must be whatever host the frontend will be served on (usually just the server URL at 443).

An example value for this would be: `https://thecombineapp.com`.

**Comment by jmgrady** [comment]
So, if I understand correctly, we need to define the same environment variable for the backend service in the non-docker environment and mimic the changes to the nginx configuration in the apache configuration, correct?

**Comment by johnthagen** [comment]
When we finish #817 I'll have a better answer for you, but the only thing I know we'll need to do for the Apache stack is just set this ENV variable so that `dotnet` picks it up when Kestrel starts.

Might not need any changes to NGINX and Apache itself (testing NGINX now).

**Comment by johnthagen** [comment]
@jmgrady For Apache (and we'll want to test this on QA of course) I think you will want the following ENV variable set such that the `dotnet` (backend) process reads it:

`COMBINE_CORS_ORIGIN=https://<SERVER_NAME>`

Where `<SERVER_NAME>` is the domain name (e.g. `thecombineapp.com`) that the server is being hosted at. No port number is necessary as the frontend is served on 443 by default.

**Comment by johnthagen** [comment]
Given the plan to the remove the non-Docker based production in (#953), this issue no longer needs to be completed.
