### ISSUE TITLE
Can't login or register in Firefox

### ISSUE THREAD

**Issue by SimeonSIL** [sillsdev/TheCombine#83]
npm debug console: `System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: An unknown error occurred while processing the certificate`

Firefox console: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:5001/v1/users/authenticate. (Reason: CORS request did not succeed).`

**Comment by SamDelaney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix sign-in/login in Firefox](https://trello.com/c/Pg9tNp5y/87-fix-sign-in-login-in-firefox)

**Comment by Micah-Schiewe** [comment]
This fundamentally stems from FireFox not trusting our self-signed certificate for a CORS request, and thus rejecting it. That'll be fixed when we deploy, as then we'll have a valid certificate. Thus, fixing it now isn't really a priority.
