### ISSUE TITLE
User avatars not removed from browser after database wipe

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#848]
1. Drop database
2. Create a new user
3. Add an avatar
4. Log out
5. Drop database
6. Delete ~/.CombineFiles
7. Disable cache on browser
8. Create a new user
9. Log in

You will see the original user's avatar. This might have to do with how we respond to that request or some other caching with React DOM interaction.

**Comment by johnthagen** [comment]
<img width="955" alt="cache" src="https://user-images.githubusercontent.com/10340167/101208434-2fa3c180-3640-11eb-8b7d-1ac27d01361d.png">

**Comment by imnasnainaec** [comment]
The avatar also persists if you log out and back in with a different user.
