### ISSUE TITLE
Avatar not shown on login or on change

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#879]
1. Create a user
2. Log in
3. Add an avatar
4. Log out
5. Log in
6. The avatar is not shown in the top bar until you click on the User icon

**Comment by johnthagen** [comment]
In general this issue happens when you first set the avatar as well. The actual picture isn't updated until you click something in the app bar, such as The Combine to go back to the main page.

**Comment by imnasnainaec** [comment]
The async login function that pulls the user avatar from the database and saves it to localStorage tends to complete after the UserMenu has already loaded for the first time, so the avatar doesn't show up until the UserMenu or one of its parents components has a different reason to update.

**Comment by johnthagen** [comment]
Is there a way for something to "kick" the UI refresh after the avatar has loaded?

**Comment by imnasnainaec** [comment]
Possible solution: add a value in the store state that changes when an update has been made to the avatar in local storage.

**Comment by johnthagen** [comment]
Related to #848 / #866

**Comment by imnasnainaec** [comment]
The easiest fix would be to add an await in the login process for the avatar to load. Is that an acceptable login delay, @jasonleenaylor?

**Comment by johnthagen** [comment]
@imnasnainaec I can no longer reproduce this bug locally. Perhaps some changes in the past year have improved/fixed this situation.

I'm inclined to close if you are.

**Comment by imnasnainaec** [comment]
> @imnasnainaec I can no longer reproduce this bug locally. Perhaps some changes in the past year have improved/fixed this situation.
> 
> I'm inclined to close if you are.
Ah, you're right that it does show in the AppBar on login. However, the logo in the AppBar doesn't immediately update when a (new) avatar is uploaded. This isn't as big of a deal, since the new avatar *is* visible in the UserSettings page and appears in the app bar as soon as you navigate away from the UserSettings page.
