### ISSUE TITLE
Refresh in a step breaks goal selector

### ISSUE THREAD

**Issue by Rapdorian** [sillsdev/TheCombine#93]
## Reproduction

- Go to any step other than Create Character Inventory
- Refresh the page
- It will send you to Create Character Inventory

**Comment by tyasw** [comment]
When I render a goal inside a component, I get the id of the visible component from the store, then find a component that matches that id. When you navigate to a random route, the visible component id has not been set.

**Comment by SamDelaney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix refreshing a goal page loading the wrong component](https://trello.com/c/qldYRyGq/93-fix-refreshing-a-goal-page-loading-the-wrong-component)

**Comment by tyasw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Persist Redux store beyond browser refresh](https://trello.com/c/iBUhRHoU/136-persist-redux-store-beyond-browser-refresh)

**Comment by tyasw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Load correct component when loading a goal](https://trello.com/c/inuAV3GB/179-load-correct-component-when-loading-a-goal)
