### ISSUE TITLE
Consider skipping slow formatting of translation dictionaries

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#932]
These take a long time for Prettier to format, which forces the developer to wait quite some time for `npm run fmt-frontend` to finish:

```
src\resources\dictionaries\en-us.aff.ts 4ms
src\resources\dictionaries\en-us.dic.ts 550ms
src\resources\dictionaries\es.aff.ts 1146ms
src\resources\dictionaries\es.dic.ts 42485ms
src\resources\dictionaries\fr.aff.ts 32ms
src\resources\dictionaries\fr.dic.ts 1594ms
src\resources\dictionaries\index.ts 3ms
```

**Comment by imnasnainaec** [comment]
Would it be worthwhile to have a .prettierignore file and write a script that `npm run fmt-frontend` would consult?

**Comment by johnthagen** [comment]
Yeah, I think a `.prettierignore` file would be ideal. Perhaps we just ignore `src\resources\dictionaries\*`

**Comment by imnasnainaec** [comment]
Haha. I didn't know that `.prettierignore` was actually a thing. I made that up, expecting we'd have to write a custom script, but its existence has made this easy.
