### ISSUE TITLE
Improve download-ready UI

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#937]
"Click “Export” button and see green circle; also need to click download arrow to download (whilst green circle is still circling). However, download arrow is not so obvious, particularly on wide screen monitor and since green circle is still circling, the user may not realise that step 1 of the process is complete and that user interaction is required for step 2."
\# 1 on https://docs.google.com/document/d/1d3Cvt4FjCC1TxlVAYyun4K1qtFL1dx3S-wv2aCcPBmU

Also: UI improvements needed for download-in-progress (for large exports).

Also: On error, more detail of why it errored or what the user should do next would be useful.

**Comment by johnthagen** [comment]
I have had similar thoughts about the UI being a little confusing as well.

What if we did this:

1 . User hits Export, the button
2. Export button spins green, but do not show another icon yet.
3. When export is complete, change the Export button text to "Download"
4. After download is complete change button text back to "Export"

This removes the extra button complication, and hopefully could make things simpler.

**Comment by imnasnainaec** [comment]
> I have had similar thoughts about the UI being a little confusing as well.
> 
> What if we did this:
> 
> 1 . User hits Export, the button
> 2. Export button spins green, but do not show another icon yet.
> 3. When export is complete, change the Export button text to "Download"
> 4. After download is complete change button text back to "Export"
> 
> This removes the extra button complication, and hopefully could make things simpler.

The extra button is still needed for the AppBar, because a user doesn't need to stay on the export page while the project is exporting. However, it indeed might be better for the Export button to become a download button if/when the export is successful.
