### ISSUE TITLE
History doesn't work with direct navigation

### ISSUE THREAD

**Issue by Rapdorian** [sillsdev/TheCombine#94]
## Reproduction

- Go to any step
- Go back to the goal selector from the URL bar [localhost:3000/goals](http://localhost:3000/goals)
- The history fails to update

**Comment by tyasw** [comment]
I believe this is related to the Redux store not persisting beyond a single browser session.

**Comment by SamDelaney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [History doesn't work with direct navigation #94](https://trello.com/c/p6WKzdpH/96-history-doesnt-work-with-direct-navigation-94)

**Comment by SimeonSIL** [comment]
#122
