### ISSUE TITLE
Download should have meaningful name after unzipped.

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#941]
The LIFT export zip file downloaded by the user is named in the frontend according to #800 with project name and a timestamp. However, the unzipped folder is simply `Lift` and the files within are `NewLiftFile.lift` and `NewLiftFile.lift-ranges`. These should at least have the project name (if not also a timestamp).

**Comment by jasonleenaylor** [comment]
It is common in a file exported from FieldWorks for the lift file name to match the folder that the user chose for the export. This is just a convention though, as seen by our export if they don't match there is no issue loading the data. The filename for the .lift and .lift-ranges must match. The nicest thing for us to do would be to have the Folder and File names match the project name (sanitized for valid filename characters).
