### ISSUE TITLE
/docs User Guide 404

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#946]
Once the react-router activates, https://thecombine.languagetechnology.org/docs is 404: Page not found.

**Comment by johnthagen** [comment]
Strangely, one time after I disabling cache in Chrome dev tools, the user menu User Guide link took me to: https://localhost/app/docs (clearly a 404) rather than https://localhost/docs. I was not able to reproduce it however.

**Comment by imnasnainaec** [comment]
Resolved by #954
