### ISSUE TITLE
Backend test randomly fails

### ISSUE THREAD

**Issue by SamDelaney** [sillsdev/TheCombine#95]
Random string generator sometimes adds invalid characters to file names in TestLiftImports

**Comment by SamDelaney** [comment]
[https://build.palaso.org/viewLog.html?buildId=154977&buildTypeId=TheCombineUnitTests&tab=buildLog&branch_TheCombine=pull%2F75&_focus=176](url)

**Comment by Rapdorian** [comment]
Fixed
