### ISSUE TITLE
Remove deploy/ subproject after migration to Docker

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#953]
Once we fully transition to a Docker-based deployment, we should be able to:

- Remove `deploy`  folder and the previous Apache-based install
- Rename `docker_deploy` to `deploy`

**Comment by johnthagen** [comment]
We should also be able to remove the backend needing to run on HTTPS port 5001, as local development can just use HTTP 5000 and production uses HTTP behind NGINX reverse proxy.

**Comment by imnasnainaec** [comment]
... and `public/.htaccess`.

**Comment by johnthagen** [comment]
Also `docs/deploy`.

**Comment by imnasnainaec** [comment]
Will #825 need to be updated/closed?

**Comment by johnthagen** [comment]
> Will #825 need to be updated/closed?

I closed it. It is no longer needed given we are proceeding with this issue.
