### ISSUE TITLE
Track word modification time and export DateModified and DateCreated to LIFT

### ISSUE THREAD

**Issue by jasonleenaylor** [sillsdev/TheCombine#960]
In order to do clean-up after exporting from The Combine it is useful to be able to sort by the last modified date.

Currently words created in The Combine do not store their DateCreated and when a word is changed (sense added or deleted, semantic domain added or removed) we do not store the DateModified.

We need to update our model to include this data and export it in the Lift file.

Acceptance Tests:

- [x] DateCreated in a Lift Export for a word created in The Combine matches the date/time that it was created and not the export time
- [x] DateModified in a Lift Export for a word created in The Combine matches the date/time that a semantic domain or a new sense is added.
- [x] A word that was added through Lift Import retains its original DateCreated and DateModified values on a Lift Export.
- [x] A word that was added through Lift Import and has a semantic domain added retains its original DateCreated value but has an updated DateModified value

**Comment by johnthagen** [comment]
> We need to update our model to include this data and export it in the Lift file.

The `Word` model has the following attributes already that we should be able to use. I will look into why they are not being updated properly.

```c#
        [BsonElement("created")]
        public string Created { get; set; }

        [BsonElement("modified")]
        public string Modified { get; set; }
```

**Comment by johnthagen** [comment]
Frontend ways to create/update words:

- Data Entry
- Review Entries (change glosses/domains)
- Merge Duplicates

**Comment by johnthagen** [comment]
#990  will need to be resolved before too much progress can be made to the Merge Duplicates section of the backend.
