### ISSUE TITLE
Consider removing several MergeWords fields

### ISSUE THREAD

**Issue by johnthagen** [sillsdev/TheCombine#965]
These fields in `MergeWords` are currently unused and seem redundant:

```cs
    public class MergeWords
    {
        public string MergedBy { get; set; }
        public string Time { get; set; }
    }
```

- `MergedBy`: Should we simply use the currently logged in `User.Name`/`User.Username` if this is every needed in the future?
- `Time`: The backend can query for the current time itself. This reduces risk of time being configured differently in the frontend and being inconsistent with the rest of the backend-generated timestamps.

**Comment by jasonleenaylor** [comment]
Yes, I think this is reasonable. The model object was created as part of the plan to show meaningful history. As they are currently unused and it seems we can handle it without them I'm happy for them to go.
